// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rebac/v1/relationships.proto

package api.relations.v1;

public interface DeleteRelationshipsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.rebac.v1.DeleteRelationshipsResponse)
    com.google.protobuf.MessageOrBuilder {
}
