// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rebac/v1/relationships.proto

package api.relations.v1;

public interface ReadRelationshipsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.rebac.v1.ReadRelationshipsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .api.rebac.v1.Relationship relationships = 1;</code>
   */
  java.util.List<api.relations.v1.Relationship> 
      getRelationshipsList();
  /**
   * <code>repeated .api.rebac.v1.Relationship relationships = 1;</code>
   */
  api.relations.v1.Relationship getRelationships(int index);
  /**
   * <code>repeated .api.rebac.v1.Relationship relationships = 1;</code>
   */
  int getRelationshipsCount();
  /**
   * <code>repeated .api.rebac.v1.Relationship relationships = 1;</code>
   */
  java.util.List<? extends api.relations.v1.RelationshipOrBuilder> 
      getRelationshipsOrBuilderList();
  /**
   * <code>repeated .api.rebac.v1.Relationship relationships = 1;</code>
   */
  api.relations.v1.RelationshipOrBuilder getRelationshipsOrBuilder(
      int index);
}
