// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: kessel/relations/v1beta1/check.proto

package org.project_kessel.api.relations.v1beta1;


/**
* Validates {@code CheckResponse} protobuf objects.
*/
@SuppressWarnings("all")
public class CheckResponseValidator implements io.envoyproxy.pgv.ValidatorImpl<org.project_kessel.api.relations.v1beta1.CheckResponse>{
	public static io.envoyproxy.pgv.ValidatorImpl validatorFor(Class clazz) {
		if (clazz.equals(org.project_kessel.api.relations.v1beta1.CheckResponse.class)) return new CheckResponseValidator();
		
		return null;
	}
		
	
	
	

	public void assertValid(org.project_kessel.api.relations.v1beta1.CheckResponse proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	// no validation rules for Allowed

	
	
	}

}

