// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kessel/relations/v1beta1/check.proto

// Protobuf Java Version: 3.25.1
package org.project_kessel.api.relations.v1beta1;

public interface CheckResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kessel.relations.v1beta1.CheckResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.kessel.relations.v1beta1.CheckResponse.Allowed allowed = 1 [json_name = "allowed"];</code>
   * @return The enum numeric value on the wire for allowed.
   */
  int getAllowedValue();
  /**
   * <code>.kessel.relations.v1beta1.CheckResponse.Allowed allowed = 1 [json_name = "allowed"];</code>
   * @return The allowed.
   */
  org.project_kessel.api.relations.v1beta1.CheckResponse.Allowed getAllowed();
}
