// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kessel/relations/v1beta1/check.proto

// Protobuf Java Version: 3.25.1
package org.project_kessel.api.relations.v1beta1;

/**
 * Protobuf type {@code kessel.relations.v1beta1.CheckRequest}
 */
public final class CheckRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:kessel.relations.v1beta1.CheckRequest)
    CheckRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CheckRequest.newBuilder() to construct.
  private CheckRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CheckRequest() {
    relation_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CheckRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.project_kessel.api.relations.v1beta1.Check.internal_static_kessel_relations_v1beta1_CheckRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.project_kessel.api.relations.v1beta1.Check.internal_static_kessel_relations_v1beta1_CheckRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.project_kessel.api.relations.v1beta1.CheckRequest.class, org.project_kessel.api.relations.v1beta1.CheckRequest.Builder.class);
  }

  private int bitField0_;
  public static final int RESOURCE_FIELD_NUMBER = 1;
  private org.project_kessel.api.relations.v1beta1.ObjectReference resource_;
  /**
   * <code>.kessel.relations.v1beta1.ObjectReference resource = 1 [json_name = "resource", (.validate.rules) = { ... }</code>
   * @return Whether the resource field is set.
   */
  @java.lang.Override
  public boolean hasResource() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.kessel.relations.v1beta1.ObjectReference resource = 1 [json_name = "resource", (.validate.rules) = { ... }</code>
   * @return The resource.
   */
  @java.lang.Override
  public org.project_kessel.api.relations.v1beta1.ObjectReference getResource() {
    return resource_ == null ? org.project_kessel.api.relations.v1beta1.ObjectReference.getDefaultInstance() : resource_;
  }
  /**
   * <code>.kessel.relations.v1beta1.ObjectReference resource = 1 [json_name = "resource", (.validate.rules) = { ... }</code>
   */
  @java.lang.Override
  public org.project_kessel.api.relations.v1beta1.ObjectReferenceOrBuilder getResourceOrBuilder() {
    return resource_ == null ? org.project_kessel.api.relations.v1beta1.ObjectReference.getDefaultInstance() : resource_;
  }

  public static final int RELATION_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object relation_ = "";
  /**
   * <code>string relation = 2 [json_name = "relation", (.validate.rules) = { ... }</code>
   * @return The relation.
   */
  @java.lang.Override
  public java.lang.String getRelation() {
    java.lang.Object ref = relation_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      relation_ = s;
      return s;
    }
  }
  /**
   * <code>string relation = 2 [json_name = "relation", (.validate.rules) = { ... }</code>
   * @return The bytes for relation.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRelationBytes() {
    java.lang.Object ref = relation_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      relation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUBJECT_FIELD_NUMBER = 3;
  private org.project_kessel.api.relations.v1beta1.SubjectReference subject_;
  /**
   * <code>.kessel.relations.v1beta1.SubjectReference subject = 3 [json_name = "subject", (.validate.rules) = { ... }</code>
   * @return Whether the subject field is set.
   */
  @java.lang.Override
  public boolean hasSubject() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.kessel.relations.v1beta1.SubjectReference subject = 3 [json_name = "subject", (.validate.rules) = { ... }</code>
   * @return The subject.
   */
  @java.lang.Override
  public org.project_kessel.api.relations.v1beta1.SubjectReference getSubject() {
    return subject_ == null ? org.project_kessel.api.relations.v1beta1.SubjectReference.getDefaultInstance() : subject_;
  }
  /**
   * <code>.kessel.relations.v1beta1.SubjectReference subject = 3 [json_name = "subject", (.validate.rules) = { ... }</code>
   */
  @java.lang.Override
  public org.project_kessel.api.relations.v1beta1.SubjectReferenceOrBuilder getSubjectOrBuilder() {
    return subject_ == null ? org.project_kessel.api.relations.v1beta1.SubjectReference.getDefaultInstance() : subject_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getResource());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(relation_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, relation_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getSubject());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getResource());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(relation_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, relation_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getSubject());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.project_kessel.api.relations.v1beta1.CheckRequest)) {
      return super.equals(obj);
    }
    org.project_kessel.api.relations.v1beta1.CheckRequest other = (org.project_kessel.api.relations.v1beta1.CheckRequest) obj;

    if (hasResource() != other.hasResource()) return false;
    if (hasResource()) {
      if (!getResource()
          .equals(other.getResource())) return false;
    }
    if (!getRelation()
        .equals(other.getRelation())) return false;
    if (hasSubject() != other.hasSubject()) return false;
    if (hasSubject()) {
      if (!getSubject()
          .equals(other.getSubject())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasResource()) {
      hash = (37 * hash) + RESOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getResource().hashCode();
    }
    hash = (37 * hash) + RELATION_FIELD_NUMBER;
    hash = (53 * hash) + getRelation().hashCode();
    if (hasSubject()) {
      hash = (37 * hash) + SUBJECT_FIELD_NUMBER;
      hash = (53 * hash) + getSubject().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.project_kessel.api.relations.v1beta1.CheckRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.relations.v1beta1.CheckRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.relations.v1beta1.CheckRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.relations.v1beta1.CheckRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.relations.v1beta1.CheckRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.relations.v1beta1.CheckRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.relations.v1beta1.CheckRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.project_kessel.api.relations.v1beta1.CheckRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.project_kessel.api.relations.v1beta1.CheckRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.project_kessel.api.relations.v1beta1.CheckRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.project_kessel.api.relations.v1beta1.CheckRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.project_kessel.api.relations.v1beta1.CheckRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.project_kessel.api.relations.v1beta1.CheckRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code kessel.relations.v1beta1.CheckRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kessel.relations.v1beta1.CheckRequest)
      org.project_kessel.api.relations.v1beta1.CheckRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.project_kessel.api.relations.v1beta1.Check.internal_static_kessel_relations_v1beta1_CheckRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.project_kessel.api.relations.v1beta1.Check.internal_static_kessel_relations_v1beta1_CheckRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.project_kessel.api.relations.v1beta1.CheckRequest.class, org.project_kessel.api.relations.v1beta1.CheckRequest.Builder.class);
    }

    // Construct using org.project_kessel.api.relations.v1beta1.CheckRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getResourceFieldBuilder();
        getSubjectFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      resource_ = null;
      if (resourceBuilder_ != null) {
        resourceBuilder_.dispose();
        resourceBuilder_ = null;
      }
      relation_ = "";
      subject_ = null;
      if (subjectBuilder_ != null) {
        subjectBuilder_.dispose();
        subjectBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.project_kessel.api.relations.v1beta1.Check.internal_static_kessel_relations_v1beta1_CheckRequest_descriptor;
    }

    @java.lang.Override
    public org.project_kessel.api.relations.v1beta1.CheckRequest getDefaultInstanceForType() {
      return org.project_kessel.api.relations.v1beta1.CheckRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.project_kessel.api.relations.v1beta1.CheckRequest build() {
      org.project_kessel.api.relations.v1beta1.CheckRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.project_kessel.api.relations.v1beta1.CheckRequest buildPartial() {
      org.project_kessel.api.relations.v1beta1.CheckRequest result = new org.project_kessel.api.relations.v1beta1.CheckRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.project_kessel.api.relations.v1beta1.CheckRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.resource_ = resourceBuilder_ == null
            ? resource_
            : resourceBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.relation_ = relation_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.subject_ = subjectBuilder_ == null
            ? subject_
            : subjectBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.project_kessel.api.relations.v1beta1.CheckRequest) {
        return mergeFrom((org.project_kessel.api.relations.v1beta1.CheckRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.project_kessel.api.relations.v1beta1.CheckRequest other) {
      if (other == org.project_kessel.api.relations.v1beta1.CheckRequest.getDefaultInstance()) return this;
      if (other.hasResource()) {
        mergeResource(other.getResource());
      }
      if (!other.getRelation().isEmpty()) {
        relation_ = other.relation_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasSubject()) {
        mergeSubject(other.getSubject());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getResourceFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              relation_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getSubjectFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private org.project_kessel.api.relations.v1beta1.ObjectReference resource_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.project_kessel.api.relations.v1beta1.ObjectReference, org.project_kessel.api.relations.v1beta1.ObjectReference.Builder, org.project_kessel.api.relations.v1beta1.ObjectReferenceOrBuilder> resourceBuilder_;
    /**
     * <code>.kessel.relations.v1beta1.ObjectReference resource = 1 [json_name = "resource", (.validate.rules) = { ... }</code>
     * @return Whether the resource field is set.
     */
    public boolean hasResource() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.kessel.relations.v1beta1.ObjectReference resource = 1 [json_name = "resource", (.validate.rules) = { ... }</code>
     * @return The resource.
     */
    public org.project_kessel.api.relations.v1beta1.ObjectReference getResource() {
      if (resourceBuilder_ == null) {
        return resource_ == null ? org.project_kessel.api.relations.v1beta1.ObjectReference.getDefaultInstance() : resource_;
      } else {
        return resourceBuilder_.getMessage();
      }
    }
    /**
     * <code>.kessel.relations.v1beta1.ObjectReference resource = 1 [json_name = "resource", (.validate.rules) = { ... }</code>
     */
    public Builder setResource(org.project_kessel.api.relations.v1beta1.ObjectReference value) {
      if (resourceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        resource_ = value;
      } else {
        resourceBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.relations.v1beta1.ObjectReference resource = 1 [json_name = "resource", (.validate.rules) = { ... }</code>
     */
    public Builder setResource(
        org.project_kessel.api.relations.v1beta1.ObjectReference.Builder builderForValue) {
      if (resourceBuilder_ == null) {
        resource_ = builderForValue.build();
      } else {
        resourceBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.relations.v1beta1.ObjectReference resource = 1 [json_name = "resource", (.validate.rules) = { ... }</code>
     */
    public Builder mergeResource(org.project_kessel.api.relations.v1beta1.ObjectReference value) {
      if (resourceBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          resource_ != null &&
          resource_ != org.project_kessel.api.relations.v1beta1.ObjectReference.getDefaultInstance()) {
          getResourceBuilder().mergeFrom(value);
        } else {
          resource_ = value;
        }
      } else {
        resourceBuilder_.mergeFrom(value);
      }
      if (resource_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.kessel.relations.v1beta1.ObjectReference resource = 1 [json_name = "resource", (.validate.rules) = { ... }</code>
     */
    public Builder clearResource() {
      bitField0_ = (bitField0_ & ~0x00000001);
      resource_ = null;
      if (resourceBuilder_ != null) {
        resourceBuilder_.dispose();
        resourceBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.relations.v1beta1.ObjectReference resource = 1 [json_name = "resource", (.validate.rules) = { ... }</code>
     */
    public org.project_kessel.api.relations.v1beta1.ObjectReference.Builder getResourceBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getResourceFieldBuilder().getBuilder();
    }
    /**
     * <code>.kessel.relations.v1beta1.ObjectReference resource = 1 [json_name = "resource", (.validate.rules) = { ... }</code>
     */
    public org.project_kessel.api.relations.v1beta1.ObjectReferenceOrBuilder getResourceOrBuilder() {
      if (resourceBuilder_ != null) {
        return resourceBuilder_.getMessageOrBuilder();
      } else {
        return resource_ == null ?
            org.project_kessel.api.relations.v1beta1.ObjectReference.getDefaultInstance() : resource_;
      }
    }
    /**
     * <code>.kessel.relations.v1beta1.ObjectReference resource = 1 [json_name = "resource", (.validate.rules) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.project_kessel.api.relations.v1beta1.ObjectReference, org.project_kessel.api.relations.v1beta1.ObjectReference.Builder, org.project_kessel.api.relations.v1beta1.ObjectReferenceOrBuilder> 
        getResourceFieldBuilder() {
      if (resourceBuilder_ == null) {
        resourceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.project_kessel.api.relations.v1beta1.ObjectReference, org.project_kessel.api.relations.v1beta1.ObjectReference.Builder, org.project_kessel.api.relations.v1beta1.ObjectReferenceOrBuilder>(
                getResource(),
                getParentForChildren(),
                isClean());
        resource_ = null;
      }
      return resourceBuilder_;
    }

    private java.lang.Object relation_ = "";
    /**
     * <code>string relation = 2 [json_name = "relation", (.validate.rules) = { ... }</code>
     * @return The relation.
     */
    public java.lang.String getRelation() {
      java.lang.Object ref = relation_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        relation_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string relation = 2 [json_name = "relation", (.validate.rules) = { ... }</code>
     * @return The bytes for relation.
     */
    public com.google.protobuf.ByteString
        getRelationBytes() {
      java.lang.Object ref = relation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        relation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string relation = 2 [json_name = "relation", (.validate.rules) = { ... }</code>
     * @param value The relation to set.
     * @return This builder for chaining.
     */
    public Builder setRelation(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      relation_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string relation = 2 [json_name = "relation", (.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearRelation() {
      relation_ = getDefaultInstance().getRelation();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string relation = 2 [json_name = "relation", (.validate.rules) = { ... }</code>
     * @param value The bytes for relation to set.
     * @return This builder for chaining.
     */
    public Builder setRelationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      relation_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private org.project_kessel.api.relations.v1beta1.SubjectReference subject_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.project_kessel.api.relations.v1beta1.SubjectReference, org.project_kessel.api.relations.v1beta1.SubjectReference.Builder, org.project_kessel.api.relations.v1beta1.SubjectReferenceOrBuilder> subjectBuilder_;
    /**
     * <code>.kessel.relations.v1beta1.SubjectReference subject = 3 [json_name = "subject", (.validate.rules) = { ... }</code>
     * @return Whether the subject field is set.
     */
    public boolean hasSubject() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.kessel.relations.v1beta1.SubjectReference subject = 3 [json_name = "subject", (.validate.rules) = { ... }</code>
     * @return The subject.
     */
    public org.project_kessel.api.relations.v1beta1.SubjectReference getSubject() {
      if (subjectBuilder_ == null) {
        return subject_ == null ? org.project_kessel.api.relations.v1beta1.SubjectReference.getDefaultInstance() : subject_;
      } else {
        return subjectBuilder_.getMessage();
      }
    }
    /**
     * <code>.kessel.relations.v1beta1.SubjectReference subject = 3 [json_name = "subject", (.validate.rules) = { ... }</code>
     */
    public Builder setSubject(org.project_kessel.api.relations.v1beta1.SubjectReference value) {
      if (subjectBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        subject_ = value;
      } else {
        subjectBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.relations.v1beta1.SubjectReference subject = 3 [json_name = "subject", (.validate.rules) = { ... }</code>
     */
    public Builder setSubject(
        org.project_kessel.api.relations.v1beta1.SubjectReference.Builder builderForValue) {
      if (subjectBuilder_ == null) {
        subject_ = builderForValue.build();
      } else {
        subjectBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.relations.v1beta1.SubjectReference subject = 3 [json_name = "subject", (.validate.rules) = { ... }</code>
     */
    public Builder mergeSubject(org.project_kessel.api.relations.v1beta1.SubjectReference value) {
      if (subjectBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          subject_ != null &&
          subject_ != org.project_kessel.api.relations.v1beta1.SubjectReference.getDefaultInstance()) {
          getSubjectBuilder().mergeFrom(value);
        } else {
          subject_ = value;
        }
      } else {
        subjectBuilder_.mergeFrom(value);
      }
      if (subject_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.kessel.relations.v1beta1.SubjectReference subject = 3 [json_name = "subject", (.validate.rules) = { ... }</code>
     */
    public Builder clearSubject() {
      bitField0_ = (bitField0_ & ~0x00000004);
      subject_ = null;
      if (subjectBuilder_ != null) {
        subjectBuilder_.dispose();
        subjectBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.relations.v1beta1.SubjectReference subject = 3 [json_name = "subject", (.validate.rules) = { ... }</code>
     */
    public org.project_kessel.api.relations.v1beta1.SubjectReference.Builder getSubjectBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getSubjectFieldBuilder().getBuilder();
    }
    /**
     * <code>.kessel.relations.v1beta1.SubjectReference subject = 3 [json_name = "subject", (.validate.rules) = { ... }</code>
     */
    public org.project_kessel.api.relations.v1beta1.SubjectReferenceOrBuilder getSubjectOrBuilder() {
      if (subjectBuilder_ != null) {
        return subjectBuilder_.getMessageOrBuilder();
      } else {
        return subject_ == null ?
            org.project_kessel.api.relations.v1beta1.SubjectReference.getDefaultInstance() : subject_;
      }
    }
    /**
     * <code>.kessel.relations.v1beta1.SubjectReference subject = 3 [json_name = "subject", (.validate.rules) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.project_kessel.api.relations.v1beta1.SubjectReference, org.project_kessel.api.relations.v1beta1.SubjectReference.Builder, org.project_kessel.api.relations.v1beta1.SubjectReferenceOrBuilder> 
        getSubjectFieldBuilder() {
      if (subjectBuilder_ == null) {
        subjectBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.project_kessel.api.relations.v1beta1.SubjectReference, org.project_kessel.api.relations.v1beta1.SubjectReference.Builder, org.project_kessel.api.relations.v1beta1.SubjectReferenceOrBuilder>(
                getSubject(),
                getParentForChildren(),
                isClean());
        subject_ = null;
      }
      return subjectBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:kessel.relations.v1beta1.CheckRequest)
  }

  // @@protoc_insertion_point(class_scope:kessel.relations.v1beta1.CheckRequest)
  private static final org.project_kessel.api.relations.v1beta1.CheckRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.project_kessel.api.relations.v1beta1.CheckRequest();
  }

  public static org.project_kessel.api.relations.v1beta1.CheckRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CheckRequest>
      PARSER = new com.google.protobuf.AbstractParser<CheckRequest>() {
    @java.lang.Override
    public CheckRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CheckRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CheckRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.project_kessel.api.relations.v1beta1.CheckRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

