// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: kessel/relations/v1beta1/check.proto

package org.project_kessel.api.relations.v1beta1;


/**
* Validates {@code CheckRequest} protobuf objects.
*/
@SuppressWarnings("all")
public class CheckRequestValidator implements io.envoyproxy.pgv.ValidatorImpl<org.project_kessel.api.relations.v1beta1.CheckRequest>{
	public static io.envoyproxy.pgv.ValidatorImpl validatorFor(Class clazz) {
		if (clazz.equals(org.project_kessel.api.relations.v1beta1.CheckRequest.class)) return new CheckRequestValidator();
		
		return null;
	}
		
	
		
	
		
	
	
	

	public void assertValid(org.project_kessel.api.relations.v1beta1.CheckRequest proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	
		if (proto.hasResource()) {
			io.envoyproxy.pgv.RequiredValidation.required(".kessel.relations.v1beta1.CheckRequest.resource", proto.getResource());
		} else {
			io.envoyproxy.pgv.RequiredValidation.required(".kessel.relations.v1beta1.CheckRequest.resource", null);
		};
	
			io.envoyproxy.pgv.StringValidation.minLength(".kessel.relations.v1beta1.CheckRequest.relation", proto.getRelation(), 1);
	
		if (proto.hasSubject()) {
			io.envoyproxy.pgv.RequiredValidation.required(".kessel.relations.v1beta1.CheckRequest.subject", proto.getSubject());
		} else {
			io.envoyproxy.pgv.RequiredValidation.required(".kessel.relations.v1beta1.CheckRequest.subject", null);
		};
	
	
	}

}

