// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kessel/relations/v1beta1/common.proto

// Protobuf Java Version: 3.25.1
package org.project_kessel.api.relations.v1beta1;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kessel_relations_v1beta1_Relationship_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kessel_relations_v1beta1_Relationship_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kessel_relations_v1beta1_SubjectReference_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kessel_relations_v1beta1_SubjectReference_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kessel_relations_v1beta1_RequestPagination_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kessel_relations_v1beta1_RequestPagination_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kessel_relations_v1beta1_ResponsePagination_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kessel_relations_v1beta1_ResponsePagination_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kessel_relations_v1beta1_ObjectReference_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kessel_relations_v1beta1_ObjectReference_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kessel_relations_v1beta1_ObjectType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kessel_relations_v1beta1_ObjectType_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%kessel/relations/v1beta1/common.proto\022" +
      "\030kessel.relations.v1beta1\032\027validate/vali" +
      "date.proto\"\324\001\n\014Relationship\022O\n\010resource\030" +
      "\001 \001(\0132).kessel.relations.v1beta1.ObjectR" +
      "eferenceB\010\372B\005\242\001\002\010\001R\010resource\022#\n\010relation" +
      "\030\002 \001(\tB\007\372B\004r\002\020\001R\010relation\022N\n\007subject\030\003 \001" +
      "(\0132*.kessel.relations.v1beta1.SubjectRef" +
      "erenceB\010\372B\005\242\001\002\010\001R\007subject\"\217\001\n\020SubjectRef" +
      "erence\022\037\n\010relation\030\001 \001(\tH\000R\010relation\210\001\001\022" +
      "M\n\007subject\030\002 \001(\0132).kessel.relations.v1be" +
      "ta1.ObjectReferenceB\010\372B\005\242\001\002\010\001R\007subjectB\013" +
      "\n\t_relation\"}\n\021RequestPagination\022\035\n\005limi" +
      "t\030\001 \001(\rB\007\372B\004*\002 \000R\005limit\0222\n\022continuation_" +
      "token\030\002 \001(\tH\000R\021continuationToken\210\001\001B\025\n\023_" +
      "continuation_token\"C\n\022ResponsePagination" +
      "\022-\n\022continuation_token\030\001 \001(\tR\021continuati" +
      "onToken\"n\n\017ObjectReference\022B\n\004type\030\001 \001(\013" +
      "2$.kessel.relations.v1beta1.ObjectTypeB\010" +
      "\372B\005\242\001\002\010\001R\004type\022\027\n\002id\030\002 \001(\tB\007\372B\004r\002\020\001R\002id\"" +
      "P\n\nObjectType\022%\n\tnamespace\030\001 \001(\tB\007\372B\004r\002\020" +
      "\001R\tnamespace\022\033\n\004name\030\002 \001(\tB\007\372B\004r\002\020\001R\004nam" +
      "eBr\n(org.project_kessel.api.relations.v1" +
      "beta1P\001ZDgithub.com/project-kessel/relat" +
      "ions-api/api/kessel/relations/v1beta1b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.envoyproxy.pgv.validate.Validate.getDescriptor(),
        });
    internal_static_kessel_relations_v1beta1_Relationship_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_kessel_relations_v1beta1_Relationship_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kessel_relations_v1beta1_Relationship_descriptor,
        new java.lang.String[] { "Resource", "Relation", "Subject", });
    internal_static_kessel_relations_v1beta1_SubjectReference_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_kessel_relations_v1beta1_SubjectReference_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kessel_relations_v1beta1_SubjectReference_descriptor,
        new java.lang.String[] { "Relation", "Subject", });
    internal_static_kessel_relations_v1beta1_RequestPagination_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_kessel_relations_v1beta1_RequestPagination_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kessel_relations_v1beta1_RequestPagination_descriptor,
        new java.lang.String[] { "Limit", "ContinuationToken", });
    internal_static_kessel_relations_v1beta1_ResponsePagination_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_kessel_relations_v1beta1_ResponsePagination_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kessel_relations_v1beta1_ResponsePagination_descriptor,
        new java.lang.String[] { "ContinuationToken", });
    internal_static_kessel_relations_v1beta1_ObjectReference_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_kessel_relations_v1beta1_ObjectReference_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kessel_relations_v1beta1_ObjectReference_descriptor,
        new java.lang.String[] { "Type", "Id", });
    internal_static_kessel_relations_v1beta1_ObjectType_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_kessel_relations_v1beta1_ObjectType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kessel_relations_v1beta1_ObjectType_descriptor,
        new java.lang.String[] { "Namespace", "Name", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(io.envoyproxy.pgv.validate.Validate.rules);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    io.envoyproxy.pgv.validate.Validate.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
