// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: kessel/relations/v1beta1/relation_tuples.proto

package org.project_kessel.api.relations.v1beta1;


/**
* Validates {@code CreateTuplesRequest} protobuf objects.
*/
@SuppressWarnings("all")
public class CreateTuplesRequestValidator implements io.envoyproxy.pgv.ValidatorImpl<org.project_kessel.api.relations.v1beta1.CreateTuplesRequest>{
	public static io.envoyproxy.pgv.ValidatorImpl validatorFor(Class clazz) {
		if (clazz.equals(org.project_kessel.api.relations.v1beta1.CreateTuplesRequest.class)) return new CreateTuplesRequestValidator();
		
		return null;
	}
		
	
		
	
	
	

	public void assertValid(org.project_kessel.api.relations.v1beta1.CreateTuplesRequest proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	// no validation rules for Upsert

	
			io.envoyproxy.pgv.RepeatedValidation.forEach(proto.getTuplesList(), item -> {
				
			// Validate tuples
			if (true) index.validatorFor(item).assertValid(item);
			});
	
	
	}

}

