// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kessel/relations/v1beta1/relation_tuples.proto

// Protobuf Java Version: 3.25.1
package org.project_kessel.api.relations.v1beta1;

public interface CreateTuplesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kessel.relations.v1beta1.CreateTuplesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Whether or not the request should ignore existing tuples (`true`),
   * or if the request should fail if the same tuple already exists (`false`).
   * 
   * Defaults to `false`.
   * </pre>
   *
   * <code>bool upsert = 1 [json_name = "upsert"];</code>
   * @return The upsert.
   */
  boolean getUpsert();

  /**
   * <code>repeated .kessel.relations.v1beta1.Relationship tuples = 2 [json_name = "tuples"];</code>
   */
  java.util.List<org.project_kessel.api.relations.v1beta1.Relationship> 
      getTuplesList();
  /**
   * <code>repeated .kessel.relations.v1beta1.Relationship tuples = 2 [json_name = "tuples"];</code>
   */
  org.project_kessel.api.relations.v1beta1.Relationship getTuples(int index);
  /**
   * <code>repeated .kessel.relations.v1beta1.Relationship tuples = 2 [json_name = "tuples"];</code>
   */
  int getTuplesCount();
  /**
   * <code>repeated .kessel.relations.v1beta1.Relationship tuples = 2 [json_name = "tuples"];</code>
   */
  java.util.List<? extends org.project_kessel.api.relations.v1beta1.RelationshipOrBuilder> 
      getTuplesOrBuilderList();
  /**
   * <code>repeated .kessel.relations.v1beta1.Relationship tuples = 2 [json_name = "tuples"];</code>
   */
  org.project_kessel.api.relations.v1beta1.RelationshipOrBuilder getTuplesOrBuilder(
      int index);
}
