// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: kessel/relations/v1beta1/relation_tuples.proto

package org.project_kessel.api.relations.v1beta1;


/**
* Validates {@code CreateTuplesResponse} protobuf objects.
*/
@SuppressWarnings("all")
public class CreateTuplesResponseValidator implements io.envoyproxy.pgv.ValidatorImpl<org.project_kessel.api.relations.v1beta1.CreateTuplesResponse>{
	public static io.envoyproxy.pgv.ValidatorImpl validatorFor(Class clazz) {
		if (clazz.equals(org.project_kessel.api.relations.v1beta1.CreateTuplesResponse.class)) return new CreateTuplesResponseValidator();
		
		return null;
	}
	
	

	public void assertValid(org.project_kessel.api.relations.v1beta1.CreateTuplesResponse proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	
	
	}

}

