// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kessel/relations/v1beta1/relation_tuples.proto

// Protobuf Java Version: 3.25.1
package org.project_kessel.api.relations.v1beta1;

/**
 * Protobuf type {@code kessel.relations.v1beta1.DeleteTuplesRequest}
 */
public final class DeleteTuplesRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:kessel.relations.v1beta1.DeleteTuplesRequest)
    DeleteTuplesRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DeleteTuplesRequest.newBuilder() to construct.
  private DeleteTuplesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DeleteTuplesRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DeleteTuplesRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.project_kessel.api.relations.v1beta1.RelationTuples.internal_static_kessel_relations_v1beta1_DeleteTuplesRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.project_kessel.api.relations.v1beta1.RelationTuples.internal_static_kessel_relations_v1beta1_DeleteTuplesRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest.class, org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest.Builder.class);
  }

  private int bitField0_;
  public static final int FILTER_FIELD_NUMBER = 1;
  private org.project_kessel.api.relations.v1beta1.RelationTupleFilter filter_;
  /**
   * <code>.kessel.relations.v1beta1.RelationTupleFilter filter = 1 [json_name = "filter", (.validate.rules) = { ... }</code>
   * @return Whether the filter field is set.
   */
  @java.lang.Override
  public boolean hasFilter() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.kessel.relations.v1beta1.RelationTupleFilter filter = 1 [json_name = "filter", (.validate.rules) = { ... }</code>
   * @return The filter.
   */
  @java.lang.Override
  public org.project_kessel.api.relations.v1beta1.RelationTupleFilter getFilter() {
    return filter_ == null ? org.project_kessel.api.relations.v1beta1.RelationTupleFilter.getDefaultInstance() : filter_;
  }
  /**
   * <code>.kessel.relations.v1beta1.RelationTupleFilter filter = 1 [json_name = "filter", (.validate.rules) = { ... }</code>
   */
  @java.lang.Override
  public org.project_kessel.api.relations.v1beta1.RelationTupleFilterOrBuilder getFilterOrBuilder() {
    return filter_ == null ? org.project_kessel.api.relations.v1beta1.RelationTupleFilter.getDefaultInstance() : filter_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getFilter());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getFilter());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest)) {
      return super.equals(obj);
    }
    org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest other = (org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest) obj;

    if (hasFilter() != other.hasFilter()) return false;
    if (hasFilter()) {
      if (!getFilter()
          .equals(other.getFilter())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasFilter()) {
      hash = (37 * hash) + FILTER_FIELD_NUMBER;
      hash = (53 * hash) + getFilter().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code kessel.relations.v1beta1.DeleteTuplesRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kessel.relations.v1beta1.DeleteTuplesRequest)
      org.project_kessel.api.relations.v1beta1.DeleteTuplesRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.project_kessel.api.relations.v1beta1.RelationTuples.internal_static_kessel_relations_v1beta1_DeleteTuplesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.project_kessel.api.relations.v1beta1.RelationTuples.internal_static_kessel_relations_v1beta1_DeleteTuplesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest.class, org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest.Builder.class);
    }

    // Construct using org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFilterFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      filter_ = null;
      if (filterBuilder_ != null) {
        filterBuilder_.dispose();
        filterBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.project_kessel.api.relations.v1beta1.RelationTuples.internal_static_kessel_relations_v1beta1_DeleteTuplesRequest_descriptor;
    }

    @java.lang.Override
    public org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest getDefaultInstanceForType() {
      return org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest build() {
      org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest buildPartial() {
      org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest result = new org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.filter_ = filterBuilder_ == null
            ? filter_
            : filterBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest) {
        return mergeFrom((org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest other) {
      if (other == org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest.getDefaultInstance()) return this;
      if (other.hasFilter()) {
        mergeFilter(other.getFilter());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getFilterFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private org.project_kessel.api.relations.v1beta1.RelationTupleFilter filter_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.project_kessel.api.relations.v1beta1.RelationTupleFilter, org.project_kessel.api.relations.v1beta1.RelationTupleFilter.Builder, org.project_kessel.api.relations.v1beta1.RelationTupleFilterOrBuilder> filterBuilder_;
    /**
     * <code>.kessel.relations.v1beta1.RelationTupleFilter filter = 1 [json_name = "filter", (.validate.rules) = { ... }</code>
     * @return Whether the filter field is set.
     */
    public boolean hasFilter() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.kessel.relations.v1beta1.RelationTupleFilter filter = 1 [json_name = "filter", (.validate.rules) = { ... }</code>
     * @return The filter.
     */
    public org.project_kessel.api.relations.v1beta1.RelationTupleFilter getFilter() {
      if (filterBuilder_ == null) {
        return filter_ == null ? org.project_kessel.api.relations.v1beta1.RelationTupleFilter.getDefaultInstance() : filter_;
      } else {
        return filterBuilder_.getMessage();
      }
    }
    /**
     * <code>.kessel.relations.v1beta1.RelationTupleFilter filter = 1 [json_name = "filter", (.validate.rules) = { ... }</code>
     */
    public Builder setFilter(org.project_kessel.api.relations.v1beta1.RelationTupleFilter value) {
      if (filterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        filter_ = value;
      } else {
        filterBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.relations.v1beta1.RelationTupleFilter filter = 1 [json_name = "filter", (.validate.rules) = { ... }</code>
     */
    public Builder setFilter(
        org.project_kessel.api.relations.v1beta1.RelationTupleFilter.Builder builderForValue) {
      if (filterBuilder_ == null) {
        filter_ = builderForValue.build();
      } else {
        filterBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.relations.v1beta1.RelationTupleFilter filter = 1 [json_name = "filter", (.validate.rules) = { ... }</code>
     */
    public Builder mergeFilter(org.project_kessel.api.relations.v1beta1.RelationTupleFilter value) {
      if (filterBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          filter_ != null &&
          filter_ != org.project_kessel.api.relations.v1beta1.RelationTupleFilter.getDefaultInstance()) {
          getFilterBuilder().mergeFrom(value);
        } else {
          filter_ = value;
        }
      } else {
        filterBuilder_.mergeFrom(value);
      }
      if (filter_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.kessel.relations.v1beta1.RelationTupleFilter filter = 1 [json_name = "filter", (.validate.rules) = { ... }</code>
     */
    public Builder clearFilter() {
      bitField0_ = (bitField0_ & ~0x00000001);
      filter_ = null;
      if (filterBuilder_ != null) {
        filterBuilder_.dispose();
        filterBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.relations.v1beta1.RelationTupleFilter filter = 1 [json_name = "filter", (.validate.rules) = { ... }</code>
     */
    public org.project_kessel.api.relations.v1beta1.RelationTupleFilter.Builder getFilterBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getFilterFieldBuilder().getBuilder();
    }
    /**
     * <code>.kessel.relations.v1beta1.RelationTupleFilter filter = 1 [json_name = "filter", (.validate.rules) = { ... }</code>
     */
    public org.project_kessel.api.relations.v1beta1.RelationTupleFilterOrBuilder getFilterOrBuilder() {
      if (filterBuilder_ != null) {
        return filterBuilder_.getMessageOrBuilder();
      } else {
        return filter_ == null ?
            org.project_kessel.api.relations.v1beta1.RelationTupleFilter.getDefaultInstance() : filter_;
      }
    }
    /**
     * <code>.kessel.relations.v1beta1.RelationTupleFilter filter = 1 [json_name = "filter", (.validate.rules) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.project_kessel.api.relations.v1beta1.RelationTupleFilter, org.project_kessel.api.relations.v1beta1.RelationTupleFilter.Builder, org.project_kessel.api.relations.v1beta1.RelationTupleFilterOrBuilder> 
        getFilterFieldBuilder() {
      if (filterBuilder_ == null) {
        filterBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.project_kessel.api.relations.v1beta1.RelationTupleFilter, org.project_kessel.api.relations.v1beta1.RelationTupleFilter.Builder, org.project_kessel.api.relations.v1beta1.RelationTupleFilterOrBuilder>(
                getFilter(),
                getParentForChildren(),
                isClean());
        filter_ = null;
      }
      return filterBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:kessel.relations.v1beta1.DeleteTuplesRequest)
  }

  // @@protoc_insertion_point(class_scope:kessel.relations.v1beta1.DeleteTuplesRequest)
  private static final org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest();
  }

  public static org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DeleteTuplesRequest>
      PARSER = new com.google.protobuf.AbstractParser<DeleteTuplesRequest>() {
    @java.lang.Override
    public DeleteTuplesRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DeleteTuplesRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DeleteTuplesRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.project_kessel.api.relations.v1beta1.DeleteTuplesRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

