// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kessel/relations/v1beta1/lookup.proto

// Protobuf Java Version: 3.25.1
package org.project_kessel.api.relations.v1beta1;

/**
 * Protobuf type {@code kessel.relations.v1beta1.LookupResourcesRequest}
 */
public final class LookupResourcesRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:kessel.relations.v1beta1.LookupResourcesRequest)
    LookupResourcesRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LookupResourcesRequest.newBuilder() to construct.
  private LookupResourcesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LookupResourcesRequest() {
    relation_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LookupResourcesRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.project_kessel.api.relations.v1beta1.Lookup.internal_static_kessel_relations_v1beta1_LookupResourcesRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.project_kessel.api.relations.v1beta1.Lookup.internal_static_kessel_relations_v1beta1_LookupResourcesRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.project_kessel.api.relations.v1beta1.LookupResourcesRequest.class, org.project_kessel.api.relations.v1beta1.LookupResourcesRequest.Builder.class);
  }

  private int bitField0_;
  public static final int RESOURCE_TYPE_FIELD_NUMBER = 1;
  private org.project_kessel.api.relations.v1beta1.ObjectType resourceType_;
  /**
   * <code>.kessel.relations.v1beta1.ObjectType resource_type = 1 [json_name = "resourceType", (.validate.rules) = { ... }</code>
   * @return Whether the resourceType field is set.
   */
  @java.lang.Override
  public boolean hasResourceType() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.kessel.relations.v1beta1.ObjectType resource_type = 1 [json_name = "resourceType", (.validate.rules) = { ... }</code>
   * @return The resourceType.
   */
  @java.lang.Override
  public org.project_kessel.api.relations.v1beta1.ObjectType getResourceType() {
    return resourceType_ == null ? org.project_kessel.api.relations.v1beta1.ObjectType.getDefaultInstance() : resourceType_;
  }
  /**
   * <code>.kessel.relations.v1beta1.ObjectType resource_type = 1 [json_name = "resourceType", (.validate.rules) = { ... }</code>
   */
  @java.lang.Override
  public org.project_kessel.api.relations.v1beta1.ObjectTypeOrBuilder getResourceTypeOrBuilder() {
    return resourceType_ == null ? org.project_kessel.api.relations.v1beta1.ObjectType.getDefaultInstance() : resourceType_;
  }

  public static final int RELATION_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object relation_ = "";
  /**
   * <code>string relation = 2 [json_name = "relation", (.validate.rules) = { ... }</code>
   * @return The relation.
   */
  @java.lang.Override
  public java.lang.String getRelation() {
    java.lang.Object ref = relation_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      relation_ = s;
      return s;
    }
  }
  /**
   * <code>string relation = 2 [json_name = "relation", (.validate.rules) = { ... }</code>
   * @return The bytes for relation.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRelationBytes() {
    java.lang.Object ref = relation_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      relation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUBJECT_FIELD_NUMBER = 3;
  private org.project_kessel.api.relations.v1beta1.SubjectReference subject_;
  /**
   * <code>.kessel.relations.v1beta1.SubjectReference subject = 3 [json_name = "subject", (.validate.rules) = { ... }</code>
   * @return Whether the subject field is set.
   */
  @java.lang.Override
  public boolean hasSubject() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.kessel.relations.v1beta1.SubjectReference subject = 3 [json_name = "subject", (.validate.rules) = { ... }</code>
   * @return The subject.
   */
  @java.lang.Override
  public org.project_kessel.api.relations.v1beta1.SubjectReference getSubject() {
    return subject_ == null ? org.project_kessel.api.relations.v1beta1.SubjectReference.getDefaultInstance() : subject_;
  }
  /**
   * <code>.kessel.relations.v1beta1.SubjectReference subject = 3 [json_name = "subject", (.validate.rules) = { ... }</code>
   */
  @java.lang.Override
  public org.project_kessel.api.relations.v1beta1.SubjectReferenceOrBuilder getSubjectOrBuilder() {
    return subject_ == null ? org.project_kessel.api.relations.v1beta1.SubjectReference.getDefaultInstance() : subject_;
  }

  public static final int PAGINATION_FIELD_NUMBER = 4;
  private org.project_kessel.api.relations.v1beta1.RequestPagination pagination_;
  /**
   * <code>optional .kessel.relations.v1beta1.RequestPagination pagination = 4 [json_name = "pagination"];</code>
   * @return Whether the pagination field is set.
   */
  @java.lang.Override
  public boolean hasPagination() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional .kessel.relations.v1beta1.RequestPagination pagination = 4 [json_name = "pagination"];</code>
   * @return The pagination.
   */
  @java.lang.Override
  public org.project_kessel.api.relations.v1beta1.RequestPagination getPagination() {
    return pagination_ == null ? org.project_kessel.api.relations.v1beta1.RequestPagination.getDefaultInstance() : pagination_;
  }
  /**
   * <code>optional .kessel.relations.v1beta1.RequestPagination pagination = 4 [json_name = "pagination"];</code>
   */
  @java.lang.Override
  public org.project_kessel.api.relations.v1beta1.RequestPaginationOrBuilder getPaginationOrBuilder() {
    return pagination_ == null ? org.project_kessel.api.relations.v1beta1.RequestPagination.getDefaultInstance() : pagination_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getResourceType());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(relation_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, relation_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getSubject());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(4, getPagination());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getResourceType());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(relation_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, relation_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getSubject());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getPagination());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.project_kessel.api.relations.v1beta1.LookupResourcesRequest)) {
      return super.equals(obj);
    }
    org.project_kessel.api.relations.v1beta1.LookupResourcesRequest other = (org.project_kessel.api.relations.v1beta1.LookupResourcesRequest) obj;

    if (hasResourceType() != other.hasResourceType()) return false;
    if (hasResourceType()) {
      if (!getResourceType()
          .equals(other.getResourceType())) return false;
    }
    if (!getRelation()
        .equals(other.getRelation())) return false;
    if (hasSubject() != other.hasSubject()) return false;
    if (hasSubject()) {
      if (!getSubject()
          .equals(other.getSubject())) return false;
    }
    if (hasPagination() != other.hasPagination()) return false;
    if (hasPagination()) {
      if (!getPagination()
          .equals(other.getPagination())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasResourceType()) {
      hash = (37 * hash) + RESOURCE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getResourceType().hashCode();
    }
    hash = (37 * hash) + RELATION_FIELD_NUMBER;
    hash = (53 * hash) + getRelation().hashCode();
    if (hasSubject()) {
      hash = (37 * hash) + SUBJECT_FIELD_NUMBER;
      hash = (53 * hash) + getSubject().hashCode();
    }
    if (hasPagination()) {
      hash = (37 * hash) + PAGINATION_FIELD_NUMBER;
      hash = (53 * hash) + getPagination().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.project_kessel.api.relations.v1beta1.LookupResourcesRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.relations.v1beta1.LookupResourcesRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.relations.v1beta1.LookupResourcesRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.relations.v1beta1.LookupResourcesRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.relations.v1beta1.LookupResourcesRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.relations.v1beta1.LookupResourcesRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.relations.v1beta1.LookupResourcesRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.project_kessel.api.relations.v1beta1.LookupResourcesRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.project_kessel.api.relations.v1beta1.LookupResourcesRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.project_kessel.api.relations.v1beta1.LookupResourcesRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.project_kessel.api.relations.v1beta1.LookupResourcesRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.project_kessel.api.relations.v1beta1.LookupResourcesRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.project_kessel.api.relations.v1beta1.LookupResourcesRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code kessel.relations.v1beta1.LookupResourcesRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kessel.relations.v1beta1.LookupResourcesRequest)
      org.project_kessel.api.relations.v1beta1.LookupResourcesRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.project_kessel.api.relations.v1beta1.Lookup.internal_static_kessel_relations_v1beta1_LookupResourcesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.project_kessel.api.relations.v1beta1.Lookup.internal_static_kessel_relations_v1beta1_LookupResourcesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.project_kessel.api.relations.v1beta1.LookupResourcesRequest.class, org.project_kessel.api.relations.v1beta1.LookupResourcesRequest.Builder.class);
    }

    // Construct using org.project_kessel.api.relations.v1beta1.LookupResourcesRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getResourceTypeFieldBuilder();
        getSubjectFieldBuilder();
        getPaginationFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      resourceType_ = null;
      if (resourceTypeBuilder_ != null) {
        resourceTypeBuilder_.dispose();
        resourceTypeBuilder_ = null;
      }
      relation_ = "";
      subject_ = null;
      if (subjectBuilder_ != null) {
        subjectBuilder_.dispose();
        subjectBuilder_ = null;
      }
      pagination_ = null;
      if (paginationBuilder_ != null) {
        paginationBuilder_.dispose();
        paginationBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.project_kessel.api.relations.v1beta1.Lookup.internal_static_kessel_relations_v1beta1_LookupResourcesRequest_descriptor;
    }

    @java.lang.Override
    public org.project_kessel.api.relations.v1beta1.LookupResourcesRequest getDefaultInstanceForType() {
      return org.project_kessel.api.relations.v1beta1.LookupResourcesRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.project_kessel.api.relations.v1beta1.LookupResourcesRequest build() {
      org.project_kessel.api.relations.v1beta1.LookupResourcesRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.project_kessel.api.relations.v1beta1.LookupResourcesRequest buildPartial() {
      org.project_kessel.api.relations.v1beta1.LookupResourcesRequest result = new org.project_kessel.api.relations.v1beta1.LookupResourcesRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.project_kessel.api.relations.v1beta1.LookupResourcesRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.resourceType_ = resourceTypeBuilder_ == null
            ? resourceType_
            : resourceTypeBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.relation_ = relation_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.subject_ = subjectBuilder_ == null
            ? subject_
            : subjectBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.pagination_ = paginationBuilder_ == null
            ? pagination_
            : paginationBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.project_kessel.api.relations.v1beta1.LookupResourcesRequest) {
        return mergeFrom((org.project_kessel.api.relations.v1beta1.LookupResourcesRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.project_kessel.api.relations.v1beta1.LookupResourcesRequest other) {
      if (other == org.project_kessel.api.relations.v1beta1.LookupResourcesRequest.getDefaultInstance()) return this;
      if (other.hasResourceType()) {
        mergeResourceType(other.getResourceType());
      }
      if (!other.getRelation().isEmpty()) {
        relation_ = other.relation_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasSubject()) {
        mergeSubject(other.getSubject());
      }
      if (other.hasPagination()) {
        mergePagination(other.getPagination());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getResourceTypeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              relation_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getSubjectFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getPaginationFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private org.project_kessel.api.relations.v1beta1.ObjectType resourceType_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.project_kessel.api.relations.v1beta1.ObjectType, org.project_kessel.api.relations.v1beta1.ObjectType.Builder, org.project_kessel.api.relations.v1beta1.ObjectTypeOrBuilder> resourceTypeBuilder_;
    /**
     * <code>.kessel.relations.v1beta1.ObjectType resource_type = 1 [json_name = "resourceType", (.validate.rules) = { ... }</code>
     * @return Whether the resourceType field is set.
     */
    public boolean hasResourceType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.kessel.relations.v1beta1.ObjectType resource_type = 1 [json_name = "resourceType", (.validate.rules) = { ... }</code>
     * @return The resourceType.
     */
    public org.project_kessel.api.relations.v1beta1.ObjectType getResourceType() {
      if (resourceTypeBuilder_ == null) {
        return resourceType_ == null ? org.project_kessel.api.relations.v1beta1.ObjectType.getDefaultInstance() : resourceType_;
      } else {
        return resourceTypeBuilder_.getMessage();
      }
    }
    /**
     * <code>.kessel.relations.v1beta1.ObjectType resource_type = 1 [json_name = "resourceType", (.validate.rules) = { ... }</code>
     */
    public Builder setResourceType(org.project_kessel.api.relations.v1beta1.ObjectType value) {
      if (resourceTypeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        resourceType_ = value;
      } else {
        resourceTypeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.relations.v1beta1.ObjectType resource_type = 1 [json_name = "resourceType", (.validate.rules) = { ... }</code>
     */
    public Builder setResourceType(
        org.project_kessel.api.relations.v1beta1.ObjectType.Builder builderForValue) {
      if (resourceTypeBuilder_ == null) {
        resourceType_ = builderForValue.build();
      } else {
        resourceTypeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.relations.v1beta1.ObjectType resource_type = 1 [json_name = "resourceType", (.validate.rules) = { ... }</code>
     */
    public Builder mergeResourceType(org.project_kessel.api.relations.v1beta1.ObjectType value) {
      if (resourceTypeBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          resourceType_ != null &&
          resourceType_ != org.project_kessel.api.relations.v1beta1.ObjectType.getDefaultInstance()) {
          getResourceTypeBuilder().mergeFrom(value);
        } else {
          resourceType_ = value;
        }
      } else {
        resourceTypeBuilder_.mergeFrom(value);
      }
      if (resourceType_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.kessel.relations.v1beta1.ObjectType resource_type = 1 [json_name = "resourceType", (.validate.rules) = { ... }</code>
     */
    public Builder clearResourceType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      resourceType_ = null;
      if (resourceTypeBuilder_ != null) {
        resourceTypeBuilder_.dispose();
        resourceTypeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.relations.v1beta1.ObjectType resource_type = 1 [json_name = "resourceType", (.validate.rules) = { ... }</code>
     */
    public org.project_kessel.api.relations.v1beta1.ObjectType.Builder getResourceTypeBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getResourceTypeFieldBuilder().getBuilder();
    }
    /**
     * <code>.kessel.relations.v1beta1.ObjectType resource_type = 1 [json_name = "resourceType", (.validate.rules) = { ... }</code>
     */
    public org.project_kessel.api.relations.v1beta1.ObjectTypeOrBuilder getResourceTypeOrBuilder() {
      if (resourceTypeBuilder_ != null) {
        return resourceTypeBuilder_.getMessageOrBuilder();
      } else {
        return resourceType_ == null ?
            org.project_kessel.api.relations.v1beta1.ObjectType.getDefaultInstance() : resourceType_;
      }
    }
    /**
     * <code>.kessel.relations.v1beta1.ObjectType resource_type = 1 [json_name = "resourceType", (.validate.rules) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.project_kessel.api.relations.v1beta1.ObjectType, org.project_kessel.api.relations.v1beta1.ObjectType.Builder, org.project_kessel.api.relations.v1beta1.ObjectTypeOrBuilder> 
        getResourceTypeFieldBuilder() {
      if (resourceTypeBuilder_ == null) {
        resourceTypeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.project_kessel.api.relations.v1beta1.ObjectType, org.project_kessel.api.relations.v1beta1.ObjectType.Builder, org.project_kessel.api.relations.v1beta1.ObjectTypeOrBuilder>(
                getResourceType(),
                getParentForChildren(),
                isClean());
        resourceType_ = null;
      }
      return resourceTypeBuilder_;
    }

    private java.lang.Object relation_ = "";
    /**
     * <code>string relation = 2 [json_name = "relation", (.validate.rules) = { ... }</code>
     * @return The relation.
     */
    public java.lang.String getRelation() {
      java.lang.Object ref = relation_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        relation_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string relation = 2 [json_name = "relation", (.validate.rules) = { ... }</code>
     * @return The bytes for relation.
     */
    public com.google.protobuf.ByteString
        getRelationBytes() {
      java.lang.Object ref = relation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        relation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string relation = 2 [json_name = "relation", (.validate.rules) = { ... }</code>
     * @param value The relation to set.
     * @return This builder for chaining.
     */
    public Builder setRelation(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      relation_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string relation = 2 [json_name = "relation", (.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearRelation() {
      relation_ = getDefaultInstance().getRelation();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string relation = 2 [json_name = "relation", (.validate.rules) = { ... }</code>
     * @param value The bytes for relation to set.
     * @return This builder for chaining.
     */
    public Builder setRelationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      relation_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private org.project_kessel.api.relations.v1beta1.SubjectReference subject_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.project_kessel.api.relations.v1beta1.SubjectReference, org.project_kessel.api.relations.v1beta1.SubjectReference.Builder, org.project_kessel.api.relations.v1beta1.SubjectReferenceOrBuilder> subjectBuilder_;
    /**
     * <code>.kessel.relations.v1beta1.SubjectReference subject = 3 [json_name = "subject", (.validate.rules) = { ... }</code>
     * @return Whether the subject field is set.
     */
    public boolean hasSubject() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.kessel.relations.v1beta1.SubjectReference subject = 3 [json_name = "subject", (.validate.rules) = { ... }</code>
     * @return The subject.
     */
    public org.project_kessel.api.relations.v1beta1.SubjectReference getSubject() {
      if (subjectBuilder_ == null) {
        return subject_ == null ? org.project_kessel.api.relations.v1beta1.SubjectReference.getDefaultInstance() : subject_;
      } else {
        return subjectBuilder_.getMessage();
      }
    }
    /**
     * <code>.kessel.relations.v1beta1.SubjectReference subject = 3 [json_name = "subject", (.validate.rules) = { ... }</code>
     */
    public Builder setSubject(org.project_kessel.api.relations.v1beta1.SubjectReference value) {
      if (subjectBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        subject_ = value;
      } else {
        subjectBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.relations.v1beta1.SubjectReference subject = 3 [json_name = "subject", (.validate.rules) = { ... }</code>
     */
    public Builder setSubject(
        org.project_kessel.api.relations.v1beta1.SubjectReference.Builder builderForValue) {
      if (subjectBuilder_ == null) {
        subject_ = builderForValue.build();
      } else {
        subjectBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.relations.v1beta1.SubjectReference subject = 3 [json_name = "subject", (.validate.rules) = { ... }</code>
     */
    public Builder mergeSubject(org.project_kessel.api.relations.v1beta1.SubjectReference value) {
      if (subjectBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          subject_ != null &&
          subject_ != org.project_kessel.api.relations.v1beta1.SubjectReference.getDefaultInstance()) {
          getSubjectBuilder().mergeFrom(value);
        } else {
          subject_ = value;
        }
      } else {
        subjectBuilder_.mergeFrom(value);
      }
      if (subject_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.kessel.relations.v1beta1.SubjectReference subject = 3 [json_name = "subject", (.validate.rules) = { ... }</code>
     */
    public Builder clearSubject() {
      bitField0_ = (bitField0_ & ~0x00000004);
      subject_ = null;
      if (subjectBuilder_ != null) {
        subjectBuilder_.dispose();
        subjectBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.relations.v1beta1.SubjectReference subject = 3 [json_name = "subject", (.validate.rules) = { ... }</code>
     */
    public org.project_kessel.api.relations.v1beta1.SubjectReference.Builder getSubjectBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getSubjectFieldBuilder().getBuilder();
    }
    /**
     * <code>.kessel.relations.v1beta1.SubjectReference subject = 3 [json_name = "subject", (.validate.rules) = { ... }</code>
     */
    public org.project_kessel.api.relations.v1beta1.SubjectReferenceOrBuilder getSubjectOrBuilder() {
      if (subjectBuilder_ != null) {
        return subjectBuilder_.getMessageOrBuilder();
      } else {
        return subject_ == null ?
            org.project_kessel.api.relations.v1beta1.SubjectReference.getDefaultInstance() : subject_;
      }
    }
    /**
     * <code>.kessel.relations.v1beta1.SubjectReference subject = 3 [json_name = "subject", (.validate.rules) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.project_kessel.api.relations.v1beta1.SubjectReference, org.project_kessel.api.relations.v1beta1.SubjectReference.Builder, org.project_kessel.api.relations.v1beta1.SubjectReferenceOrBuilder> 
        getSubjectFieldBuilder() {
      if (subjectBuilder_ == null) {
        subjectBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.project_kessel.api.relations.v1beta1.SubjectReference, org.project_kessel.api.relations.v1beta1.SubjectReference.Builder, org.project_kessel.api.relations.v1beta1.SubjectReferenceOrBuilder>(
                getSubject(),
                getParentForChildren(),
                isClean());
        subject_ = null;
      }
      return subjectBuilder_;
    }

    private org.project_kessel.api.relations.v1beta1.RequestPagination pagination_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.project_kessel.api.relations.v1beta1.RequestPagination, org.project_kessel.api.relations.v1beta1.RequestPagination.Builder, org.project_kessel.api.relations.v1beta1.RequestPaginationOrBuilder> paginationBuilder_;
    /**
     * <code>optional .kessel.relations.v1beta1.RequestPagination pagination = 4 [json_name = "pagination"];</code>
     * @return Whether the pagination field is set.
     */
    public boolean hasPagination() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .kessel.relations.v1beta1.RequestPagination pagination = 4 [json_name = "pagination"];</code>
     * @return The pagination.
     */
    public org.project_kessel.api.relations.v1beta1.RequestPagination getPagination() {
      if (paginationBuilder_ == null) {
        return pagination_ == null ? org.project_kessel.api.relations.v1beta1.RequestPagination.getDefaultInstance() : pagination_;
      } else {
        return paginationBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .kessel.relations.v1beta1.RequestPagination pagination = 4 [json_name = "pagination"];</code>
     */
    public Builder setPagination(org.project_kessel.api.relations.v1beta1.RequestPagination value) {
      if (paginationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pagination_ = value;
      } else {
        paginationBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional .kessel.relations.v1beta1.RequestPagination pagination = 4 [json_name = "pagination"];</code>
     */
    public Builder setPagination(
        org.project_kessel.api.relations.v1beta1.RequestPagination.Builder builderForValue) {
      if (paginationBuilder_ == null) {
        pagination_ = builderForValue.build();
      } else {
        paginationBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional .kessel.relations.v1beta1.RequestPagination pagination = 4 [json_name = "pagination"];</code>
     */
    public Builder mergePagination(org.project_kessel.api.relations.v1beta1.RequestPagination value) {
      if (paginationBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          pagination_ != null &&
          pagination_ != org.project_kessel.api.relations.v1beta1.RequestPagination.getDefaultInstance()) {
          getPaginationBuilder().mergeFrom(value);
        } else {
          pagination_ = value;
        }
      } else {
        paginationBuilder_.mergeFrom(value);
      }
      if (pagination_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .kessel.relations.v1beta1.RequestPagination pagination = 4 [json_name = "pagination"];</code>
     */
    public Builder clearPagination() {
      bitField0_ = (bitField0_ & ~0x00000008);
      pagination_ = null;
      if (paginationBuilder_ != null) {
        paginationBuilder_.dispose();
        paginationBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .kessel.relations.v1beta1.RequestPagination pagination = 4 [json_name = "pagination"];</code>
     */
    public org.project_kessel.api.relations.v1beta1.RequestPagination.Builder getPaginationBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getPaginationFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .kessel.relations.v1beta1.RequestPagination pagination = 4 [json_name = "pagination"];</code>
     */
    public org.project_kessel.api.relations.v1beta1.RequestPaginationOrBuilder getPaginationOrBuilder() {
      if (paginationBuilder_ != null) {
        return paginationBuilder_.getMessageOrBuilder();
      } else {
        return pagination_ == null ?
            org.project_kessel.api.relations.v1beta1.RequestPagination.getDefaultInstance() : pagination_;
      }
    }
    /**
     * <code>optional .kessel.relations.v1beta1.RequestPagination pagination = 4 [json_name = "pagination"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.project_kessel.api.relations.v1beta1.RequestPagination, org.project_kessel.api.relations.v1beta1.RequestPagination.Builder, org.project_kessel.api.relations.v1beta1.RequestPaginationOrBuilder> 
        getPaginationFieldBuilder() {
      if (paginationBuilder_ == null) {
        paginationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.project_kessel.api.relations.v1beta1.RequestPagination, org.project_kessel.api.relations.v1beta1.RequestPagination.Builder, org.project_kessel.api.relations.v1beta1.RequestPaginationOrBuilder>(
                getPagination(),
                getParentForChildren(),
                isClean());
        pagination_ = null;
      }
      return paginationBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:kessel.relations.v1beta1.LookupResourcesRequest)
  }

  // @@protoc_insertion_point(class_scope:kessel.relations.v1beta1.LookupResourcesRequest)
  private static final org.project_kessel.api.relations.v1beta1.LookupResourcesRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.project_kessel.api.relations.v1beta1.LookupResourcesRequest();
  }

  public static org.project_kessel.api.relations.v1beta1.LookupResourcesRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LookupResourcesRequest>
      PARSER = new com.google.protobuf.AbstractParser<LookupResourcesRequest>() {
    @java.lang.Override
    public LookupResourcesRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LookupResourcesRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LookupResourcesRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.project_kessel.api.relations.v1beta1.LookupResourcesRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

