// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kessel/relations/v1beta1/lookup.proto

// Protobuf Java Version: 3.25.1
package org.project_kessel.api.relations.v1beta1;

public interface LookupSubjectsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kessel.relations.v1beta1.LookupSubjectsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.kessel.relations.v1beta1.SubjectReference subject = 1 [json_name = "subject"];</code>
   * @return Whether the subject field is set.
   */
  boolean hasSubject();
  /**
   * <code>.kessel.relations.v1beta1.SubjectReference subject = 1 [json_name = "subject"];</code>
   * @return The subject.
   */
  org.project_kessel.api.relations.v1beta1.SubjectReference getSubject();
  /**
   * <code>.kessel.relations.v1beta1.SubjectReference subject = 1 [json_name = "subject"];</code>
   */
  org.project_kessel.api.relations.v1beta1.SubjectReferenceOrBuilder getSubjectOrBuilder();

  /**
   * <code>.kessel.relations.v1beta1.ResponsePagination pagination = 2 [json_name = "pagination"];</code>
   * @return Whether the pagination field is set.
   */
  boolean hasPagination();
  /**
   * <code>.kessel.relations.v1beta1.ResponsePagination pagination = 2 [json_name = "pagination"];</code>
   * @return The pagination.
   */
  org.project_kessel.api.relations.v1beta1.ResponsePagination getPagination();
  /**
   * <code>.kessel.relations.v1beta1.ResponsePagination pagination = 2 [json_name = "pagination"];</code>
   */
  org.project_kessel.api.relations.v1beta1.ResponsePaginationOrBuilder getPaginationOrBuilder();
}
