// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: kessel/relations/v1beta1/lookup.proto

package org.project_kessel.api.relations.v1beta1;


/**
* Validates {@code LookupSubjectsResponse} protobuf objects.
*/
@SuppressWarnings("all")
public class LookupSubjectsResponseValidator implements io.envoyproxy.pgv.ValidatorImpl<org.project_kessel.api.relations.v1beta1.LookupSubjectsResponse>{
	public static io.envoyproxy.pgv.ValidatorImpl validatorFor(Class clazz) {
		if (clazz.equals(org.project_kessel.api.relations.v1beta1.LookupSubjectsResponse.class)) return new LookupSubjectsResponseValidator();
		
		return null;
	}
		
	
		
	
	
	

	public void assertValid(org.project_kessel.api.relations.v1beta1.LookupSubjectsResponse proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	
			// Validate subject
			if (proto.hasSubject()) index.validatorFor(proto.getSubject()).assertValid(proto.getSubject());
	
			// Validate pagination
			if (proto.hasPagination()) index.validatorFor(proto.getPagination()).assertValid(proto.getPagination());
	
	
	}

}

