// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kessel/relations/v1beta1/lookup.proto

// Protobuf Java Version: 3.25.1
package org.project_kessel.api.relations.v1beta1;

public interface LookupResourcesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kessel.relations.v1beta1.LookupResourcesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.kessel.relations.v1beta1.ObjectReference resource = 1 [json_name = "resource"];</code>
   * @return Whether the resource field is set.
   */
  boolean hasResource();
  /**
   * <code>.kessel.relations.v1beta1.ObjectReference resource = 1 [json_name = "resource"];</code>
   * @return The resource.
   */
  org.project_kessel.api.relations.v1beta1.ObjectReference getResource();
  /**
   * <code>.kessel.relations.v1beta1.ObjectReference resource = 1 [json_name = "resource"];</code>
   */
  org.project_kessel.api.relations.v1beta1.ObjectReferenceOrBuilder getResourceOrBuilder();

  /**
   * <code>.kessel.relations.v1beta1.ResponsePagination pagination = 2 [json_name = "pagination"];</code>
   * @return Whether the pagination field is set.
   */
  boolean hasPagination();
  /**
   * <code>.kessel.relations.v1beta1.ResponsePagination pagination = 2 [json_name = "pagination"];</code>
   * @return The pagination.
   */
  org.project_kessel.api.relations.v1beta1.ResponsePagination getPagination();
  /**
   * <code>.kessel.relations.v1beta1.ResponsePagination pagination = 2 [json_name = "pagination"];</code>
   */
  org.project_kessel.api.relations.v1beta1.ResponsePaginationOrBuilder getPaginationOrBuilder();
}
