// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kessel/relations/v1beta1/lookup.proto

// Protobuf Java Version: 3.25.1
package org.project_kessel.api.relations.v1beta1;

/**
 * Protobuf type {@code kessel.relations.v1beta1.LookupSubjectsRequest}
 */
public final class LookupSubjectsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:kessel.relations.v1beta1.LookupSubjectsRequest)
    LookupSubjectsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LookupSubjectsRequest.newBuilder() to construct.
  private LookupSubjectsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LookupSubjectsRequest() {
    relation_ = "";
    subjectRelation_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LookupSubjectsRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.project_kessel.api.relations.v1beta1.Lookup.internal_static_kessel_relations_v1beta1_LookupSubjectsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.project_kessel.api.relations.v1beta1.Lookup.internal_static_kessel_relations_v1beta1_LookupSubjectsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest.class, org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest.Builder.class);
  }

  private int bitField0_;
  public static final int RESOURCE_FIELD_NUMBER = 1;
  private org.project_kessel.api.relations.v1beta1.ObjectReference resource_;
  /**
   * <code>.kessel.relations.v1beta1.ObjectReference resource = 1 [json_name = "resource", (.validate.rules) = { ... }</code>
   * @return Whether the resource field is set.
   */
  @java.lang.Override
  public boolean hasResource() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.kessel.relations.v1beta1.ObjectReference resource = 1 [json_name = "resource", (.validate.rules) = { ... }</code>
   * @return The resource.
   */
  @java.lang.Override
  public org.project_kessel.api.relations.v1beta1.ObjectReference getResource() {
    return resource_ == null ? org.project_kessel.api.relations.v1beta1.ObjectReference.getDefaultInstance() : resource_;
  }
  /**
   * <code>.kessel.relations.v1beta1.ObjectReference resource = 1 [json_name = "resource", (.validate.rules) = { ... }</code>
   */
  @java.lang.Override
  public org.project_kessel.api.relations.v1beta1.ObjectReferenceOrBuilder getResourceOrBuilder() {
    return resource_ == null ? org.project_kessel.api.relations.v1beta1.ObjectReference.getDefaultInstance() : resource_;
  }

  public static final int RELATION_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object relation_ = "";
  /**
   * <code>string relation = 2 [json_name = "relation", (.validate.rules) = { ... }</code>
   * @return The relation.
   */
  @java.lang.Override
  public java.lang.String getRelation() {
    java.lang.Object ref = relation_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      relation_ = s;
      return s;
    }
  }
  /**
   * <code>string relation = 2 [json_name = "relation", (.validate.rules) = { ... }</code>
   * @return The bytes for relation.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRelationBytes() {
    java.lang.Object ref = relation_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      relation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUBJECT_TYPE_FIELD_NUMBER = 3;
  private org.project_kessel.api.relations.v1beta1.ObjectType subjectType_;
  /**
   * <code>.kessel.relations.v1beta1.ObjectType subject_type = 3 [json_name = "subjectType", (.validate.rules) = { ... }</code>
   * @return Whether the subjectType field is set.
   */
  @java.lang.Override
  public boolean hasSubjectType() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.kessel.relations.v1beta1.ObjectType subject_type = 3 [json_name = "subjectType", (.validate.rules) = { ... }</code>
   * @return The subjectType.
   */
  @java.lang.Override
  public org.project_kessel.api.relations.v1beta1.ObjectType getSubjectType() {
    return subjectType_ == null ? org.project_kessel.api.relations.v1beta1.ObjectType.getDefaultInstance() : subjectType_;
  }
  /**
   * <code>.kessel.relations.v1beta1.ObjectType subject_type = 3 [json_name = "subjectType", (.validate.rules) = { ... }</code>
   */
  @java.lang.Override
  public org.project_kessel.api.relations.v1beta1.ObjectTypeOrBuilder getSubjectTypeOrBuilder() {
    return subjectType_ == null ? org.project_kessel.api.relations.v1beta1.ObjectType.getDefaultInstance() : subjectType_;
  }

  public static final int SUBJECT_RELATION_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object subjectRelation_ = "";
  /**
   * <code>optional string subject_relation = 4 [json_name = "subjectRelation"];</code>
   * @return Whether the subjectRelation field is set.
   */
  @java.lang.Override
  public boolean hasSubjectRelation() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string subject_relation = 4 [json_name = "subjectRelation"];</code>
   * @return The subjectRelation.
   */
  @java.lang.Override
  public java.lang.String getSubjectRelation() {
    java.lang.Object ref = subjectRelation_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      subjectRelation_ = s;
      return s;
    }
  }
  /**
   * <code>optional string subject_relation = 4 [json_name = "subjectRelation"];</code>
   * @return The bytes for subjectRelation.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSubjectRelationBytes() {
    java.lang.Object ref = subjectRelation_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      subjectRelation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAGINATION_FIELD_NUMBER = 5;
  private org.project_kessel.api.relations.v1beta1.RequestPagination pagination_;
  /**
   * <code>optional .kessel.relations.v1beta1.RequestPagination pagination = 5 [json_name = "pagination"];</code>
   * @return Whether the pagination field is set.
   */
  @java.lang.Override
  public boolean hasPagination() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional .kessel.relations.v1beta1.RequestPagination pagination = 5 [json_name = "pagination"];</code>
   * @return The pagination.
   */
  @java.lang.Override
  public org.project_kessel.api.relations.v1beta1.RequestPagination getPagination() {
    return pagination_ == null ? org.project_kessel.api.relations.v1beta1.RequestPagination.getDefaultInstance() : pagination_;
  }
  /**
   * <code>optional .kessel.relations.v1beta1.RequestPagination pagination = 5 [json_name = "pagination"];</code>
   */
  @java.lang.Override
  public org.project_kessel.api.relations.v1beta1.RequestPaginationOrBuilder getPaginationOrBuilder() {
    return pagination_ == null ? org.project_kessel.api.relations.v1beta1.RequestPagination.getDefaultInstance() : pagination_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getResource());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(relation_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, relation_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getSubjectType());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, subjectRelation_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(5, getPagination());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getResource());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(relation_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, relation_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getSubjectType());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, subjectRelation_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getPagination());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest)) {
      return super.equals(obj);
    }
    org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest other = (org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest) obj;

    if (hasResource() != other.hasResource()) return false;
    if (hasResource()) {
      if (!getResource()
          .equals(other.getResource())) return false;
    }
    if (!getRelation()
        .equals(other.getRelation())) return false;
    if (hasSubjectType() != other.hasSubjectType()) return false;
    if (hasSubjectType()) {
      if (!getSubjectType()
          .equals(other.getSubjectType())) return false;
    }
    if (hasSubjectRelation() != other.hasSubjectRelation()) return false;
    if (hasSubjectRelation()) {
      if (!getSubjectRelation()
          .equals(other.getSubjectRelation())) return false;
    }
    if (hasPagination() != other.hasPagination()) return false;
    if (hasPagination()) {
      if (!getPagination()
          .equals(other.getPagination())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasResource()) {
      hash = (37 * hash) + RESOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getResource().hashCode();
    }
    hash = (37 * hash) + RELATION_FIELD_NUMBER;
    hash = (53 * hash) + getRelation().hashCode();
    if (hasSubjectType()) {
      hash = (37 * hash) + SUBJECT_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getSubjectType().hashCode();
    }
    if (hasSubjectRelation()) {
      hash = (37 * hash) + SUBJECT_RELATION_FIELD_NUMBER;
      hash = (53 * hash) + getSubjectRelation().hashCode();
    }
    if (hasPagination()) {
      hash = (37 * hash) + PAGINATION_FIELD_NUMBER;
      hash = (53 * hash) + getPagination().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code kessel.relations.v1beta1.LookupSubjectsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kessel.relations.v1beta1.LookupSubjectsRequest)
      org.project_kessel.api.relations.v1beta1.LookupSubjectsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.project_kessel.api.relations.v1beta1.Lookup.internal_static_kessel_relations_v1beta1_LookupSubjectsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.project_kessel.api.relations.v1beta1.Lookup.internal_static_kessel_relations_v1beta1_LookupSubjectsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest.class, org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest.Builder.class);
    }

    // Construct using org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getResourceFieldBuilder();
        getSubjectTypeFieldBuilder();
        getPaginationFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      resource_ = null;
      if (resourceBuilder_ != null) {
        resourceBuilder_.dispose();
        resourceBuilder_ = null;
      }
      relation_ = "";
      subjectType_ = null;
      if (subjectTypeBuilder_ != null) {
        subjectTypeBuilder_.dispose();
        subjectTypeBuilder_ = null;
      }
      subjectRelation_ = "";
      pagination_ = null;
      if (paginationBuilder_ != null) {
        paginationBuilder_.dispose();
        paginationBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.project_kessel.api.relations.v1beta1.Lookup.internal_static_kessel_relations_v1beta1_LookupSubjectsRequest_descriptor;
    }

    @java.lang.Override
    public org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest getDefaultInstanceForType() {
      return org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest build() {
      org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest buildPartial() {
      org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest result = new org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.resource_ = resourceBuilder_ == null
            ? resource_
            : resourceBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.relation_ = relation_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.subjectType_ = subjectTypeBuilder_ == null
            ? subjectType_
            : subjectTypeBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.subjectRelation_ = subjectRelation_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.pagination_ = paginationBuilder_ == null
            ? pagination_
            : paginationBuilder_.build();
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest) {
        return mergeFrom((org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest other) {
      if (other == org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest.getDefaultInstance()) return this;
      if (other.hasResource()) {
        mergeResource(other.getResource());
      }
      if (!other.getRelation().isEmpty()) {
        relation_ = other.relation_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasSubjectType()) {
        mergeSubjectType(other.getSubjectType());
      }
      if (other.hasSubjectRelation()) {
        subjectRelation_ = other.subjectRelation_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.hasPagination()) {
        mergePagination(other.getPagination());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getResourceFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              relation_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getSubjectTypeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              subjectRelation_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getPaginationFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private org.project_kessel.api.relations.v1beta1.ObjectReference resource_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.project_kessel.api.relations.v1beta1.ObjectReference, org.project_kessel.api.relations.v1beta1.ObjectReference.Builder, org.project_kessel.api.relations.v1beta1.ObjectReferenceOrBuilder> resourceBuilder_;
    /**
     * <code>.kessel.relations.v1beta1.ObjectReference resource = 1 [json_name = "resource", (.validate.rules) = { ... }</code>
     * @return Whether the resource field is set.
     */
    public boolean hasResource() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.kessel.relations.v1beta1.ObjectReference resource = 1 [json_name = "resource", (.validate.rules) = { ... }</code>
     * @return The resource.
     */
    public org.project_kessel.api.relations.v1beta1.ObjectReference getResource() {
      if (resourceBuilder_ == null) {
        return resource_ == null ? org.project_kessel.api.relations.v1beta1.ObjectReference.getDefaultInstance() : resource_;
      } else {
        return resourceBuilder_.getMessage();
      }
    }
    /**
     * <code>.kessel.relations.v1beta1.ObjectReference resource = 1 [json_name = "resource", (.validate.rules) = { ... }</code>
     */
    public Builder setResource(org.project_kessel.api.relations.v1beta1.ObjectReference value) {
      if (resourceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        resource_ = value;
      } else {
        resourceBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.relations.v1beta1.ObjectReference resource = 1 [json_name = "resource", (.validate.rules) = { ... }</code>
     */
    public Builder setResource(
        org.project_kessel.api.relations.v1beta1.ObjectReference.Builder builderForValue) {
      if (resourceBuilder_ == null) {
        resource_ = builderForValue.build();
      } else {
        resourceBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.relations.v1beta1.ObjectReference resource = 1 [json_name = "resource", (.validate.rules) = { ... }</code>
     */
    public Builder mergeResource(org.project_kessel.api.relations.v1beta1.ObjectReference value) {
      if (resourceBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          resource_ != null &&
          resource_ != org.project_kessel.api.relations.v1beta1.ObjectReference.getDefaultInstance()) {
          getResourceBuilder().mergeFrom(value);
        } else {
          resource_ = value;
        }
      } else {
        resourceBuilder_.mergeFrom(value);
      }
      if (resource_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.kessel.relations.v1beta1.ObjectReference resource = 1 [json_name = "resource", (.validate.rules) = { ... }</code>
     */
    public Builder clearResource() {
      bitField0_ = (bitField0_ & ~0x00000001);
      resource_ = null;
      if (resourceBuilder_ != null) {
        resourceBuilder_.dispose();
        resourceBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.relations.v1beta1.ObjectReference resource = 1 [json_name = "resource", (.validate.rules) = { ... }</code>
     */
    public org.project_kessel.api.relations.v1beta1.ObjectReference.Builder getResourceBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getResourceFieldBuilder().getBuilder();
    }
    /**
     * <code>.kessel.relations.v1beta1.ObjectReference resource = 1 [json_name = "resource", (.validate.rules) = { ... }</code>
     */
    public org.project_kessel.api.relations.v1beta1.ObjectReferenceOrBuilder getResourceOrBuilder() {
      if (resourceBuilder_ != null) {
        return resourceBuilder_.getMessageOrBuilder();
      } else {
        return resource_ == null ?
            org.project_kessel.api.relations.v1beta1.ObjectReference.getDefaultInstance() : resource_;
      }
    }
    /**
     * <code>.kessel.relations.v1beta1.ObjectReference resource = 1 [json_name = "resource", (.validate.rules) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.project_kessel.api.relations.v1beta1.ObjectReference, org.project_kessel.api.relations.v1beta1.ObjectReference.Builder, org.project_kessel.api.relations.v1beta1.ObjectReferenceOrBuilder> 
        getResourceFieldBuilder() {
      if (resourceBuilder_ == null) {
        resourceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.project_kessel.api.relations.v1beta1.ObjectReference, org.project_kessel.api.relations.v1beta1.ObjectReference.Builder, org.project_kessel.api.relations.v1beta1.ObjectReferenceOrBuilder>(
                getResource(),
                getParentForChildren(),
                isClean());
        resource_ = null;
      }
      return resourceBuilder_;
    }

    private java.lang.Object relation_ = "";
    /**
     * <code>string relation = 2 [json_name = "relation", (.validate.rules) = { ... }</code>
     * @return The relation.
     */
    public java.lang.String getRelation() {
      java.lang.Object ref = relation_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        relation_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string relation = 2 [json_name = "relation", (.validate.rules) = { ... }</code>
     * @return The bytes for relation.
     */
    public com.google.protobuf.ByteString
        getRelationBytes() {
      java.lang.Object ref = relation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        relation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string relation = 2 [json_name = "relation", (.validate.rules) = { ... }</code>
     * @param value The relation to set.
     * @return This builder for chaining.
     */
    public Builder setRelation(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      relation_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string relation = 2 [json_name = "relation", (.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearRelation() {
      relation_ = getDefaultInstance().getRelation();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string relation = 2 [json_name = "relation", (.validate.rules) = { ... }</code>
     * @param value The bytes for relation to set.
     * @return This builder for chaining.
     */
    public Builder setRelationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      relation_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private org.project_kessel.api.relations.v1beta1.ObjectType subjectType_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.project_kessel.api.relations.v1beta1.ObjectType, org.project_kessel.api.relations.v1beta1.ObjectType.Builder, org.project_kessel.api.relations.v1beta1.ObjectTypeOrBuilder> subjectTypeBuilder_;
    /**
     * <code>.kessel.relations.v1beta1.ObjectType subject_type = 3 [json_name = "subjectType", (.validate.rules) = { ... }</code>
     * @return Whether the subjectType field is set.
     */
    public boolean hasSubjectType() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.kessel.relations.v1beta1.ObjectType subject_type = 3 [json_name = "subjectType", (.validate.rules) = { ... }</code>
     * @return The subjectType.
     */
    public org.project_kessel.api.relations.v1beta1.ObjectType getSubjectType() {
      if (subjectTypeBuilder_ == null) {
        return subjectType_ == null ? org.project_kessel.api.relations.v1beta1.ObjectType.getDefaultInstance() : subjectType_;
      } else {
        return subjectTypeBuilder_.getMessage();
      }
    }
    /**
     * <code>.kessel.relations.v1beta1.ObjectType subject_type = 3 [json_name = "subjectType", (.validate.rules) = { ... }</code>
     */
    public Builder setSubjectType(org.project_kessel.api.relations.v1beta1.ObjectType value) {
      if (subjectTypeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        subjectType_ = value;
      } else {
        subjectTypeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.relations.v1beta1.ObjectType subject_type = 3 [json_name = "subjectType", (.validate.rules) = { ... }</code>
     */
    public Builder setSubjectType(
        org.project_kessel.api.relations.v1beta1.ObjectType.Builder builderForValue) {
      if (subjectTypeBuilder_ == null) {
        subjectType_ = builderForValue.build();
      } else {
        subjectTypeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.relations.v1beta1.ObjectType subject_type = 3 [json_name = "subjectType", (.validate.rules) = { ... }</code>
     */
    public Builder mergeSubjectType(org.project_kessel.api.relations.v1beta1.ObjectType value) {
      if (subjectTypeBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          subjectType_ != null &&
          subjectType_ != org.project_kessel.api.relations.v1beta1.ObjectType.getDefaultInstance()) {
          getSubjectTypeBuilder().mergeFrom(value);
        } else {
          subjectType_ = value;
        }
      } else {
        subjectTypeBuilder_.mergeFrom(value);
      }
      if (subjectType_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.kessel.relations.v1beta1.ObjectType subject_type = 3 [json_name = "subjectType", (.validate.rules) = { ... }</code>
     */
    public Builder clearSubjectType() {
      bitField0_ = (bitField0_ & ~0x00000004);
      subjectType_ = null;
      if (subjectTypeBuilder_ != null) {
        subjectTypeBuilder_.dispose();
        subjectTypeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.relations.v1beta1.ObjectType subject_type = 3 [json_name = "subjectType", (.validate.rules) = { ... }</code>
     */
    public org.project_kessel.api.relations.v1beta1.ObjectType.Builder getSubjectTypeBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getSubjectTypeFieldBuilder().getBuilder();
    }
    /**
     * <code>.kessel.relations.v1beta1.ObjectType subject_type = 3 [json_name = "subjectType", (.validate.rules) = { ... }</code>
     */
    public org.project_kessel.api.relations.v1beta1.ObjectTypeOrBuilder getSubjectTypeOrBuilder() {
      if (subjectTypeBuilder_ != null) {
        return subjectTypeBuilder_.getMessageOrBuilder();
      } else {
        return subjectType_ == null ?
            org.project_kessel.api.relations.v1beta1.ObjectType.getDefaultInstance() : subjectType_;
      }
    }
    /**
     * <code>.kessel.relations.v1beta1.ObjectType subject_type = 3 [json_name = "subjectType", (.validate.rules) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.project_kessel.api.relations.v1beta1.ObjectType, org.project_kessel.api.relations.v1beta1.ObjectType.Builder, org.project_kessel.api.relations.v1beta1.ObjectTypeOrBuilder> 
        getSubjectTypeFieldBuilder() {
      if (subjectTypeBuilder_ == null) {
        subjectTypeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.project_kessel.api.relations.v1beta1.ObjectType, org.project_kessel.api.relations.v1beta1.ObjectType.Builder, org.project_kessel.api.relations.v1beta1.ObjectTypeOrBuilder>(
                getSubjectType(),
                getParentForChildren(),
                isClean());
        subjectType_ = null;
      }
      return subjectTypeBuilder_;
    }

    private java.lang.Object subjectRelation_ = "";
    /**
     * <code>optional string subject_relation = 4 [json_name = "subjectRelation"];</code>
     * @return Whether the subjectRelation field is set.
     */
    public boolean hasSubjectRelation() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string subject_relation = 4 [json_name = "subjectRelation"];</code>
     * @return The subjectRelation.
     */
    public java.lang.String getSubjectRelation() {
      java.lang.Object ref = subjectRelation_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subjectRelation_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string subject_relation = 4 [json_name = "subjectRelation"];</code>
     * @return The bytes for subjectRelation.
     */
    public com.google.protobuf.ByteString
        getSubjectRelationBytes() {
      java.lang.Object ref = subjectRelation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subjectRelation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string subject_relation = 4 [json_name = "subjectRelation"];</code>
     * @param value The subjectRelation to set.
     * @return This builder for chaining.
     */
    public Builder setSubjectRelation(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      subjectRelation_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional string subject_relation = 4 [json_name = "subjectRelation"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSubjectRelation() {
      subjectRelation_ = getDefaultInstance().getSubjectRelation();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>optional string subject_relation = 4 [json_name = "subjectRelation"];</code>
     * @param value The bytes for subjectRelation to set.
     * @return This builder for chaining.
     */
    public Builder setSubjectRelationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      subjectRelation_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private org.project_kessel.api.relations.v1beta1.RequestPagination pagination_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.project_kessel.api.relations.v1beta1.RequestPagination, org.project_kessel.api.relations.v1beta1.RequestPagination.Builder, org.project_kessel.api.relations.v1beta1.RequestPaginationOrBuilder> paginationBuilder_;
    /**
     * <code>optional .kessel.relations.v1beta1.RequestPagination pagination = 5 [json_name = "pagination"];</code>
     * @return Whether the pagination field is set.
     */
    public boolean hasPagination() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional .kessel.relations.v1beta1.RequestPagination pagination = 5 [json_name = "pagination"];</code>
     * @return The pagination.
     */
    public org.project_kessel.api.relations.v1beta1.RequestPagination getPagination() {
      if (paginationBuilder_ == null) {
        return pagination_ == null ? org.project_kessel.api.relations.v1beta1.RequestPagination.getDefaultInstance() : pagination_;
      } else {
        return paginationBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .kessel.relations.v1beta1.RequestPagination pagination = 5 [json_name = "pagination"];</code>
     */
    public Builder setPagination(org.project_kessel.api.relations.v1beta1.RequestPagination value) {
      if (paginationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pagination_ = value;
      } else {
        paginationBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional .kessel.relations.v1beta1.RequestPagination pagination = 5 [json_name = "pagination"];</code>
     */
    public Builder setPagination(
        org.project_kessel.api.relations.v1beta1.RequestPagination.Builder builderForValue) {
      if (paginationBuilder_ == null) {
        pagination_ = builderForValue.build();
      } else {
        paginationBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional .kessel.relations.v1beta1.RequestPagination pagination = 5 [json_name = "pagination"];</code>
     */
    public Builder mergePagination(org.project_kessel.api.relations.v1beta1.RequestPagination value) {
      if (paginationBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          pagination_ != null &&
          pagination_ != org.project_kessel.api.relations.v1beta1.RequestPagination.getDefaultInstance()) {
          getPaginationBuilder().mergeFrom(value);
        } else {
          pagination_ = value;
        }
      } else {
        paginationBuilder_.mergeFrom(value);
      }
      if (pagination_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .kessel.relations.v1beta1.RequestPagination pagination = 5 [json_name = "pagination"];</code>
     */
    public Builder clearPagination() {
      bitField0_ = (bitField0_ & ~0x00000010);
      pagination_ = null;
      if (paginationBuilder_ != null) {
        paginationBuilder_.dispose();
        paginationBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .kessel.relations.v1beta1.RequestPagination pagination = 5 [json_name = "pagination"];</code>
     */
    public org.project_kessel.api.relations.v1beta1.RequestPagination.Builder getPaginationBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getPaginationFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .kessel.relations.v1beta1.RequestPagination pagination = 5 [json_name = "pagination"];</code>
     */
    public org.project_kessel.api.relations.v1beta1.RequestPaginationOrBuilder getPaginationOrBuilder() {
      if (paginationBuilder_ != null) {
        return paginationBuilder_.getMessageOrBuilder();
      } else {
        return pagination_ == null ?
            org.project_kessel.api.relations.v1beta1.RequestPagination.getDefaultInstance() : pagination_;
      }
    }
    /**
     * <code>optional .kessel.relations.v1beta1.RequestPagination pagination = 5 [json_name = "pagination"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.project_kessel.api.relations.v1beta1.RequestPagination, org.project_kessel.api.relations.v1beta1.RequestPagination.Builder, org.project_kessel.api.relations.v1beta1.RequestPaginationOrBuilder> 
        getPaginationFieldBuilder() {
      if (paginationBuilder_ == null) {
        paginationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.project_kessel.api.relations.v1beta1.RequestPagination, org.project_kessel.api.relations.v1beta1.RequestPagination.Builder, org.project_kessel.api.relations.v1beta1.RequestPaginationOrBuilder>(
                getPagination(),
                getParentForChildren(),
                isClean());
        pagination_ = null;
      }
      return paginationBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:kessel.relations.v1beta1.LookupSubjectsRequest)
  }

  // @@protoc_insertion_point(class_scope:kessel.relations.v1beta1.LookupSubjectsRequest)
  private static final org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest();
  }

  public static org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LookupSubjectsRequest>
      PARSER = new com.google.protobuf.AbstractParser<LookupSubjectsRequest>() {
    @java.lang.Override
    public LookupSubjectsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LookupSubjectsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LookupSubjectsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.project_kessel.api.relations.v1beta1.LookupSubjectsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

