// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kessel/relations/v1beta1/lookup.proto

// Protobuf Java Version: 3.25.1
package org.project_kessel.api.relations.v1beta1;

public final class Lookup {
  private Lookup() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kessel_relations_v1beta1_LookupResourcesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kessel_relations_v1beta1_LookupResourcesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kessel_relations_v1beta1_LookupResourcesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kessel_relations_v1beta1_LookupResourcesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kessel_relations_v1beta1_LookupSubjectsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kessel_relations_v1beta1_LookupSubjectsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kessel_relations_v1beta1_LookupSubjectsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kessel_relations_v1beta1_LookupSubjectsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%kessel/relations/v1beta1/lookup.proto\022" +
      "\030kessel.relations.v1beta1\032\034google/api/an" +
      "notations.proto\032%kessel/relations/v1beta" +
      "1/common.proto\032\027validate/validate.proto\"" +
      "\303\002\n\026LookupResourcesRequest\022S\n\rresource_t" +
      "ype\030\001 \001(\0132$.kessel.relations.v1beta1.Obj" +
      "ectTypeB\010\372B\005\242\001\002\010\001R\014resourceType\022#\n\010relat" +
      "ion\030\002 \001(\tB\007\372B\004r\002\020\001R\010relation\022N\n\007subject\030" +
      "\003 \001(\0132*.kessel.relations.v1beta1.Subject" +
      "ReferenceB\010\372B\005\242\001\002\010\001R\007subject\022P\n\npaginati" +
      "on\030\004 \001(\0132+.kessel.relations.v1beta1.Requ" +
      "estPaginationH\000R\npagination\210\001\001B\r\n\013_pagin" +
      "ation\"\256\001\n\027LookupResourcesResponse\022E\n\010res" +
      "ource\030\001 \001(\0132).kessel.relations.v1beta1.O" +
      "bjectReferenceR\010resource\022L\n\npagination\030\002" +
      " \001(\0132,.kessel.relations.v1beta1.Response" +
      "PaginationR\npagination\"\206\003\n\025LookupSubject" +
      "sRequest\022O\n\010resource\030\001 \001(\0132).kessel.rela" +
      "tions.v1beta1.ObjectReferenceB\010\372B\005\242\001\002\010\001R" +
      "\010resource\022#\n\010relation\030\002 \001(\tB\007\372B\004r\002\020\001R\010re" +
      "lation\022Q\n\014subject_type\030\003 \001(\0132$.kessel.re" +
      "lations.v1beta1.ObjectTypeB\010\372B\005\242\001\002\010\001R\013su" +
      "bjectType\022.\n\020subject_relation\030\004 \001(\tH\000R\017s" +
      "ubjectRelation\210\001\001\022P\n\npagination\030\005 \001(\0132+." +
      "kessel.relations.v1beta1.RequestPaginati" +
      "onH\001R\npagination\210\001\001B\023\n\021_subject_relation" +
      "B\r\n\013_pagination\"\254\001\n\026LookupSubjectsRespon" +
      "se\022D\n\007subject\030\001 \001(\0132*.kessel.relations.v" +
      "1beta1.SubjectReferenceR\007subject\022L\n\npagi" +
      "nation\030\002 \001(\0132,.kessel.relations.v1beta1." +
      "ResponsePaginationR\npagination2\277\002\n\023Kesse" +
      "lLookupService\022\220\001\n\016LookupSubjects\022/.kess" +
      "el.relations.v1beta1.LookupSubjectsReque" +
      "st\0320.kessel.relations.v1beta1.LookupSubj" +
      "ectsResponse\"\031\202\323\344\223\002\023\022\021/v1beta1/subjects0" +
      "\001\022\224\001\n\017LookupResources\0220.kessel.relations" +
      ".v1beta1.LookupResourcesRequest\0321.kessel" +
      ".relations.v1beta1.LookupResourcesRespon" +
      "se\"\032\202\323\344\223\002\024\022\022/v1beta1/resources0\001Br\n(org." +
      "project_kessel.api.relations.v1beta1P\001ZD" +
      "github.com/project-kessel/relations-api/" +
      "api/kessel/relations/v1beta1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          org.project_kessel.api.relations.v1beta1.Common.getDescriptor(),
          io.envoyproxy.pgv.validate.Validate.getDescriptor(),
        });
    internal_static_kessel_relations_v1beta1_LookupResourcesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_kessel_relations_v1beta1_LookupResourcesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kessel_relations_v1beta1_LookupResourcesRequest_descriptor,
        new java.lang.String[] { "ResourceType", "Relation", "Subject", "Pagination", });
    internal_static_kessel_relations_v1beta1_LookupResourcesResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_kessel_relations_v1beta1_LookupResourcesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kessel_relations_v1beta1_LookupResourcesResponse_descriptor,
        new java.lang.String[] { "Resource", "Pagination", });
    internal_static_kessel_relations_v1beta1_LookupSubjectsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_kessel_relations_v1beta1_LookupSubjectsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kessel_relations_v1beta1_LookupSubjectsRequest_descriptor,
        new java.lang.String[] { "Resource", "Relation", "SubjectType", "SubjectRelation", "Pagination", });
    internal_static_kessel_relations_v1beta1_LookupSubjectsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_kessel_relations_v1beta1_LookupSubjectsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kessel_relations_v1beta1_LookupSubjectsResponse_descriptor,
        new java.lang.String[] { "Subject", "Pagination", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(io.envoyproxy.pgv.validate.Validate.rules);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    org.project_kessel.api.relations.v1beta1.Common.getDescriptor();
    io.envoyproxy.pgv.validate.Validate.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
