// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kessel/relations/v1beta1/common.proto

// Protobuf Java Version: 3.25.1
package org.project_kessel.api.relations.v1beta1;

public interface ObjectReferenceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kessel.relations.v1beta1.ObjectReference)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.kessel.relations.v1beta1.ObjectType type = 1 [json_name = "type", (.validate.rules) = { ... }</code>
   * @return Whether the type field is set.
   */
  boolean hasType();
  /**
   * <code>.kessel.relations.v1beta1.ObjectType type = 1 [json_name = "type", (.validate.rules) = { ... }</code>
   * @return The type.
   */
  org.project_kessel.api.relations.v1beta1.ObjectType getType();
  /**
   * <code>.kessel.relations.v1beta1.ObjectType type = 1 [json_name = "type", (.validate.rules) = { ... }</code>
   */
  org.project_kessel.api.relations.v1beta1.ObjectTypeOrBuilder getTypeOrBuilder();

  /**
   * <code>string id = 2 [json_name = "id", (.validate.rules) = { ... }</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 2 [json_name = "id", (.validate.rules) = { ... }</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
