// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: kessel/relations/v1beta1/common.proto

package org.project_kessel.api.relations.v1beta1;


/**
* Validates {@code ObjectType} protobuf objects.
*/
@SuppressWarnings("all")
public class ObjectTypeValidator implements io.envoyproxy.pgv.ValidatorImpl<org.project_kessel.api.relations.v1beta1.ObjectType>{
	public static io.envoyproxy.pgv.ValidatorImpl validatorFor(Class clazz) {
		if (clazz.equals(org.project_kessel.api.relations.v1beta1.ObjectType.class)) return new ObjectTypeValidator();
		
		return null;
	}
		
	
		
	
	
	

	public void assertValid(org.project_kessel.api.relations.v1beta1.ObjectType proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	
			io.envoyproxy.pgv.StringValidation.minLength(".kessel.relations.v1beta1.ObjectType.namespace", proto.getNamespace(), 1);
	
			io.envoyproxy.pgv.StringValidation.minLength(".kessel.relations.v1beta1.ObjectType.name", proto.getName(), 1);
	
	
	}

}

