// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kessel/relations/v1beta1/common.proto

// Protobuf Java Version: 3.25.1
package org.project_kessel.api.relations.v1beta1;

public interface ObjectTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kessel.relations.v1beta1.ObjectType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string namespace = 1 [json_name = "namespace", (.validate.rules) = { ... }</code>
   * @return The namespace.
   */
  java.lang.String getNamespace();
  /**
   * <code>string namespace = 1 [json_name = "namespace", (.validate.rules) = { ... }</code>
   * @return The bytes for namespace.
   */
  com.google.protobuf.ByteString
      getNamespaceBytes();

  /**
   * <code>string name = 2 [json_name = "name", (.validate.rules) = { ... }</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2 [json_name = "name", (.validate.rules) = { ... }</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
