// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: kessel/relations/v1beta1/common.proto

package org.project_kessel.api.relations.v1beta1;


/**
* Validates {@code ObjectReference} protobuf objects.
*/
@SuppressWarnings("all")
public class ObjectReferenceValidator implements io.envoyproxy.pgv.ValidatorImpl<org.project_kessel.api.relations.v1beta1.ObjectReference>{
	public static io.envoyproxy.pgv.ValidatorImpl validatorFor(Class clazz) {
		if (clazz.equals(org.project_kessel.api.relations.v1beta1.ObjectReference.class)) return new ObjectReferenceValidator();
		
		return null;
	}
		
	
		
	
	
	

	public void assertValid(org.project_kessel.api.relations.v1beta1.ObjectReference proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	
		if (proto.hasType()) {
			io.envoyproxy.pgv.RequiredValidation.required(".kessel.relations.v1beta1.ObjectReference.type", proto.getType());
		} else {
			io.envoyproxy.pgv.RequiredValidation.required(".kessel.relations.v1beta1.ObjectReference.type", null);
		};
	
			io.envoyproxy.pgv.StringValidation.minLength(".kessel.relations.v1beta1.ObjectReference.id", proto.getId(), 1);
	
	
	}

}

