// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: kessel/relations/v1beta1/relation_tuples.proto

package org.project_kessel.api.relations.v1beta1;


/**
* Validates {@code ReadTuplesRequest} protobuf objects.
*/
@SuppressWarnings("all")
public class ReadTuplesRequestValidator implements io.envoyproxy.pgv.ValidatorImpl<org.project_kessel.api.relations.v1beta1.ReadTuplesRequest>{
	public static io.envoyproxy.pgv.ValidatorImpl validatorFor(Class clazz) {
		if (clazz.equals(org.project_kessel.api.relations.v1beta1.ReadTuplesRequest.class)) return new ReadTuplesRequestValidator();
		
		return null;
	}
		
	
	
		
	
	

	public void assertValid(org.project_kessel.api.relations.v1beta1.ReadTuplesRequest proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	
		if (proto.hasFilter()) {
			io.envoyproxy.pgv.RequiredValidation.required(".kessel.relations.v1beta1.ReadTuplesRequest.filter", proto.getFilter());
		} else {
			io.envoyproxy.pgv.RequiredValidation.required(".kessel.relations.v1beta1.ReadTuplesRequest.filter", null);
		};
	
		if (proto.hasPagination()) {
			
			// Validate pagination
			if (proto.hasPagination()) index.validatorFor(proto.getPagination()).assertValid(proto.getPagination());
		}
	
	
	}

}

