// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: kessel/relations/v1beta1/relation_tuples.proto

package org.project_kessel.api.relations.v1beta1;


/**
* Validates {@code ReadTuplesResponse} protobuf objects.
*/
@SuppressWarnings("all")
public class ReadTuplesResponseValidator implements io.envoyproxy.pgv.ValidatorImpl<org.project_kessel.api.relations.v1beta1.ReadTuplesResponse>{
	public static io.envoyproxy.pgv.ValidatorImpl validatorFor(Class clazz) {
		if (clazz.equals(org.project_kessel.api.relations.v1beta1.ReadTuplesResponse.class)) return new ReadTuplesResponseValidator();
		
		return null;
	}
		
	
		
	
	
	

	public void assertValid(org.project_kessel.api.relations.v1beta1.ReadTuplesResponse proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	
			// Validate tuple
			if (proto.hasTuple()) index.validatorFor(proto.getTuple()).assertValid(proto.getTuple());
	
			// Validate pagination
			if (proto.hasPagination()) index.validatorFor(proto.getPagination()).assertValid(proto.getPagination());
	
	
	}

}

