// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: kessel/relations/v1beta1/relation_tuples.proto

package org.project_kessel.api.relations.v1beta1;


/**
* Validates {@code RelationTupleFilter} protobuf objects.
*/
@SuppressWarnings("all")
public class RelationTupleFilterValidator implements io.envoyproxy.pgv.ValidatorImpl<org.project_kessel.api.relations.v1beta1.RelationTupleFilter>{
	public static io.envoyproxy.pgv.ValidatorImpl validatorFor(Class clazz) {
		if (clazz.equals(org.project_kessel.api.relations.v1beta1.RelationTupleFilter.class)) return new RelationTupleFilterValidator();
		
		return null;
	}
	
		
	
		
	
		
	
		
	
		
	
	

	public void assertValid(org.project_kessel.api.relations.v1beta1.RelationTupleFilter proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	
		if (proto.hasResourceNamespace()) {
			// no validation rules for ResourceNamespace

		}
	
		if (proto.hasResourceType()) {
			// no validation rules for ResourceType

		}
	
		if (proto.hasResourceId()) {
			// no validation rules for ResourceId

		}
	
		if (proto.hasRelation()) {
			// no validation rules for Relation

		}
	
		if (proto.hasSubjectFilter()) {
			
			// Validate subject_filter
			if (proto.hasSubjectFilter()) index.validatorFor(proto.getSubjectFilter()).assertValid(proto.getSubjectFilter());
		}
	
	
	}

}

