// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kessel/relations/v1beta1/relation_tuples.proto

// Protobuf Java Version: 3.25.1
package org.project_kessel.api.relations.v1beta1;

public interface RelationTupleFilterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kessel.relations.v1beta1.RelationTupleFilter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string resource_namespace = 1 [json_name = "resourceNamespace"];</code>
   * @return Whether the resourceNamespace field is set.
   */
  boolean hasResourceNamespace();
  /**
   * <code>optional string resource_namespace = 1 [json_name = "resourceNamespace"];</code>
   * @return The resourceNamespace.
   */
  java.lang.String getResourceNamespace();
  /**
   * <code>optional string resource_namespace = 1 [json_name = "resourceNamespace"];</code>
   * @return The bytes for resourceNamespace.
   */
  com.google.protobuf.ByteString
      getResourceNamespaceBytes();

  /**
   * <code>optional string resource_type = 2 [json_name = "resourceType"];</code>
   * @return Whether the resourceType field is set.
   */
  boolean hasResourceType();
  /**
   * <code>optional string resource_type = 2 [json_name = "resourceType"];</code>
   * @return The resourceType.
   */
  java.lang.String getResourceType();
  /**
   * <code>optional string resource_type = 2 [json_name = "resourceType"];</code>
   * @return The bytes for resourceType.
   */
  com.google.protobuf.ByteString
      getResourceTypeBytes();

  /**
   * <code>optional string resource_id = 3 [json_name = "resourceId"];</code>
   * @return Whether the resourceId field is set.
   */
  boolean hasResourceId();
  /**
   * <code>optional string resource_id = 3 [json_name = "resourceId"];</code>
   * @return The resourceId.
   */
  java.lang.String getResourceId();
  /**
   * <code>optional string resource_id = 3 [json_name = "resourceId"];</code>
   * @return The bytes for resourceId.
   */
  com.google.protobuf.ByteString
      getResourceIdBytes();

  /**
   * <code>optional string relation = 4 [json_name = "relation"];</code>
   * @return Whether the relation field is set.
   */
  boolean hasRelation();
  /**
   * <code>optional string relation = 4 [json_name = "relation"];</code>
   * @return The relation.
   */
  java.lang.String getRelation();
  /**
   * <code>optional string relation = 4 [json_name = "relation"];</code>
   * @return The bytes for relation.
   */
  com.google.protobuf.ByteString
      getRelationBytes();

  /**
   * <code>optional .kessel.relations.v1beta1.SubjectFilter subject_filter = 5 [json_name = "subjectFilter"];</code>
   * @return Whether the subjectFilter field is set.
   */
  boolean hasSubjectFilter();
  /**
   * <code>optional .kessel.relations.v1beta1.SubjectFilter subject_filter = 5 [json_name = "subjectFilter"];</code>
   * @return The subjectFilter.
   */
  org.project_kessel.api.relations.v1beta1.SubjectFilter getSubjectFilter();
  /**
   * <code>optional .kessel.relations.v1beta1.SubjectFilter subject_filter = 5 [json_name = "subjectFilter"];</code>
   */
  org.project_kessel.api.relations.v1beta1.SubjectFilterOrBuilder getSubjectFilterOrBuilder();
}
