// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kessel/relations/v1beta1/common.proto

// Protobuf Java Version: 3.25.1
package org.project_kessel.api.relations.v1beta1;

public interface RequestPaginationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kessel.relations.v1beta1.RequestPagination)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 limit = 1 [json_name = "limit", (.validate.rules) = { ... }</code>
   * @return The limit.
   */
  int getLimit();

  /**
   * <code>optional string continuation_token = 2 [json_name = "continuationToken"];</code>
   * @return Whether the continuationToken field is set.
   */
  boolean hasContinuationToken();
  /**
   * <code>optional string continuation_token = 2 [json_name = "continuationToken"];</code>
   * @return The continuationToken.
   */
  java.lang.String getContinuationToken();
  /**
   * <code>optional string continuation_token = 2 [json_name = "continuationToken"];</code>
   * @return The bytes for continuationToken.
   */
  com.google.protobuf.ByteString
      getContinuationTokenBytes();
}
