// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kessel/relations/v1beta1/common.proto

// Protobuf Java Version: 3.25.1
package org.project_kessel.api.relations.v1beta1;

public interface ResponsePaginationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kessel.relations.v1beta1.ResponsePagination)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string continuation_token = 1 [json_name = "continuationToken"];</code>
   * @return The continuationToken.
   */
  java.lang.String getContinuationToken();
  /**
   * <code>string continuation_token = 1 [json_name = "continuationToken"];</code>
   * @return The bytes for continuationToken.
   */
  com.google.protobuf.ByteString
      getContinuationTokenBytes();
}
