// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: kessel/relations/v1beta1/common.proto

package org.project_kessel.api.relations.v1beta1;


/**
* Validates {@code ResponsePagination} protobuf objects.
*/
@SuppressWarnings("all")
public class ResponsePaginationValidator implements io.envoyproxy.pgv.ValidatorImpl<org.project_kessel.api.relations.v1beta1.ResponsePagination>{
	public static io.envoyproxy.pgv.ValidatorImpl validatorFor(Class clazz) {
		if (clazz.equals(org.project_kessel.api.relations.v1beta1.ResponsePagination.class)) return new ResponsePaginationValidator();
		
		return null;
	}
		
	
	
	

	public void assertValid(org.project_kessel.api.relations.v1beta1.ResponsePagination proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	// no validation rules for ContinuationToken

	
	
	}

}

