// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: kessel/relations/v1beta1/relation_tuples.proto

package org.project_kessel.api.relations.v1beta1;


/**
* Validates {@code SubjectFilter} protobuf objects.
*/
@SuppressWarnings("all")
public class SubjectFilterValidator implements io.envoyproxy.pgv.ValidatorImpl<org.project_kessel.api.relations.v1beta1.SubjectFilter>{
	public static io.envoyproxy.pgv.ValidatorImpl validatorFor(Class clazz) {
		if (clazz.equals(org.project_kessel.api.relations.v1beta1.SubjectFilter.class)) return new SubjectFilterValidator();
		
		return null;
	}
	
		
	
		
	
		
	
		
	
	

	public void assertValid(org.project_kessel.api.relations.v1beta1.SubjectFilter proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	
		if (proto.hasSubjectNamespace()) {
			// no validation rules for SubjectNamespace

		}
	
		if (proto.hasSubjectType()) {
			// no validation rules for SubjectType

		}
	
		if (proto.hasSubjectId()) {
			// no validation rules for SubjectId

		}
	
		if (proto.hasRelation()) {
			// no validation rules for Relation

		}
	
	
	}

}

