// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kessel/relations/v1beta1/common.proto

// Protobuf Java Version: 3.25.1
package org.project_kessel.api.relations.v1beta1;

public interface SubjectReferenceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kessel.relations.v1beta1.SubjectReference)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * An optional relation which points to a set of Subjects instead of the single Subject.
   * e.g. "members" or "owners" of a group identified in `subject`.
   * </pre>
   *
   * <code>optional string relation = 1 [json_name = "relation"];</code>
   * @return Whether the relation field is set.
   */
  boolean hasRelation();
  /**
   * <pre>
   * An optional relation which points to a set of Subjects instead of the single Subject.
   * e.g. "members" or "owners" of a group identified in `subject`.
   * </pre>
   *
   * <code>optional string relation = 1 [json_name = "relation"];</code>
   * @return The relation.
   */
  java.lang.String getRelation();
  /**
   * <pre>
   * An optional relation which points to a set of Subjects instead of the single Subject.
   * e.g. "members" or "owners" of a group identified in `subject`.
   * </pre>
   *
   * <code>optional string relation = 1 [json_name = "relation"];</code>
   * @return The bytes for relation.
   */
  com.google.protobuf.ByteString
      getRelationBytes();

  /**
   * <code>.kessel.relations.v1beta1.ObjectReference subject = 2 [json_name = "subject", (.validate.rules) = { ... }</code>
   * @return Whether the subject field is set.
   */
  boolean hasSubject();
  /**
   * <code>.kessel.relations.v1beta1.ObjectReference subject = 2 [json_name = "subject", (.validate.rules) = { ... }</code>
   * @return The subject.
   */
  org.project_kessel.api.relations.v1beta1.ObjectReference getSubject();
  /**
   * <code>.kessel.relations.v1beta1.ObjectReference subject = 2 [json_name = "subject", (.validate.rules) = { ... }</code>
   */
  org.project_kessel.api.relations.v1beta1.ObjectReferenceOrBuilder getSubjectOrBuilder();
}
