// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: kessel/relations/v1beta1/common.proto

package org.project_kessel.api.relations.v1beta1;


/**
* Validates {@code SubjectReference} protobuf objects.
*/
@SuppressWarnings("all")
public class SubjectReferenceValidator implements io.envoyproxy.pgv.ValidatorImpl<org.project_kessel.api.relations.v1beta1.SubjectReference>{
	public static io.envoyproxy.pgv.ValidatorImpl validatorFor(Class clazz) {
		if (clazz.equals(org.project_kessel.api.relations.v1beta1.SubjectReference.class)) return new SubjectReferenceValidator();
		
		return null;
	}
		
	
	
		
	
	

	public void assertValid(org.project_kessel.api.relations.v1beta1.SubjectReference proto, io.envoyproxy.pgv.ValidatorIndex index) throws io.envoyproxy.pgv.ValidationException {
	
		if (proto.hasSubject()) {
			io.envoyproxy.pgv.RequiredValidation.required(".kessel.relations.v1beta1.SubjectReference.subject", proto.getSubject());
		} else {
			io.envoyproxy.pgv.RequiredValidation.required(".kessel.relations.v1beta1.SubjectReference.subject", null);
		};
	
		if (proto.hasRelation()) {
			// no validation rules for Relation

		}
	
	
	}

}

