// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: health/v1/health.proto

package api.health.v1;

public interface GetLivezReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.health.v1.GetLivezReply)
    com.google.protobuf.MessageOrBuilder {
}
