// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kessel/health/v1/health.proto

// Protobuf Java Version: 3.25.1
package org.project_kessel.api.relations.v1;

public interface GetLivezRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kessel.health.v1.GetLivezRequest)
    com.google.protobuf.MessageOrBuilder {
}
