// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kessel/relations/v1/health.proto

// Protobuf Java Version: 3.25.1
package org.project_kessel.api.relations.v1;

public interface GetReadyzResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kessel.relations.v1.GetReadyzResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1 [json_name = "status"];</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1 [json_name = "status"];</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>uint32 code = 2 [json_name = "code"];</code>
   * @return The code.
   */
  int getCode();
}
