// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rebac/v1/check.proto

package api.check.v1;

public interface CheckResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.rebac.v1.CheckResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.api.rebac.v1.CheckResponse.Allowed allowed = 1;</code>
   * @return The enum numeric value on the wire for allowed.
   */
  int getAllowedValue();
  /**
   * <code>.api.rebac.v1.CheckResponse.Allowed allowed = 1;</code>
   * @return The allowed.
   */
  api.check.v1.CheckResponse.Allowed getAllowed();
}
